In [1]:
import importlib
import numpy as np

In [2]:
import sys
print(sys.path)

['', 'C:\\Shahar\\BarIlan\\NLP-courses\\89687-DL\\Assignment1\\code', 'C:\\Shahar\\BarIlan\\NLP-courses\\89687-DL\\Assignment1', 'C:\\ProgramData\\Anaconda3\\envs\\bari_env\\python36.zip', 'C:\\ProgramData\\Anaconda3\\envs\\bari_env\\DLLs', 'C:\\ProgramData\\Anaconda3\\envs\\bari_env\\lib', 'C:\\ProgramData\\Anaconda3\\envs\\bari_env', 'C:\\ProgramData\\Anaconda3\\envs\\bari_env\\lib\\site-packages', 'C:\\ProgramData\\Anaconda3\\envs\\bari_env\\lib\\site-packages\\IPython\\extensions', 'C:\\Users\\Shahar\\.ipython']


In [3]:
sys.path.append('C:\\Shahar\\BarIlan\\NLP-courses\\89687-DL\\Assignment1\\code')

In [4]:
print(sys.path)

['', 'C:\\Shahar\\BarIlan\\NLP-courses\\89687-DL\\Assignment1\\code', 'C:\\Shahar\\BarIlan\\NLP-courses\\89687-DL\\Assignment1', 'C:\\ProgramData\\Anaconda3\\envs\\bari_env\\python36.zip', 'C:\\ProgramData\\Anaconda3\\envs\\bari_env\\DLLs', 'C:\\ProgramData\\Anaconda3\\envs\\bari_env\\lib', 'C:\\ProgramData\\Anaconda3\\envs\\bari_env', 'C:\\ProgramData\\Anaconda3\\envs\\bari_env\\lib\\site-packages', 'C:\\ProgramData\\Anaconda3\\envs\\bari_env\\lib\\site-packages\\IPython\\extensions', 'C:\\Users\\Shahar\\.ipython', 'C:\\Shahar\\BarIlan\\NLP-courses\\89687-DL\\Assignment1\\code']


In [5]:
import testing
importlib.reload(testing)
import loglinear
importlib.reload(loglinear)
import grad_check
importlib.reload(grad_check)


<module 'grad_check' from 'C:\\Shahar\\BarIlan\\NLP-courses\\89687-DL\\Assignment1\\code\\grad_check.py'>

In [7]:
loss_gb = testing.grad_sanity()
W,b = testing.create_classifier(3,6)
print(W)


Gradient check passed!
Gradient check passed!
Gradient check passed!
Gradient check passed!
Gradient check passed!
Gradient check passed!
Gradient check passed!
Gradient check passed!
Gradient check passed!
Gradient check passed!
Gradient check passed!
Gradient check passed!
Gradient check passed!
Gradient check passed!
Gradient check passed!
Gradient check passed!
Gradient check passed!
Gradient check passed!
Gradient check passed!
Gradient check passed!
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [10]:
loglinear.logloss(np.array([0,1,0]),np.array([0.333333,0.4333,0.2333]))

0.8363249502362733

In [12]:
importlib.reload(testing)
#importlib.reload(loglinear)
#importlib.reload(grad_check)
p = testing.grad_sanity()

Gradient check passed!
Gradient check passed!
Gradient check passed!
Gradient check passed!
Gradient check passed!
Gradient check passed!
Gradient check passed!
Gradient check passed!
Gradient check passed!
Gradient check passed!
Gradient check passed!
Gradient check passed!
Gradient check passed!
Gradient check passed!
Gradient check passed!
Gradient check passed!
Gradient check passed!
Gradient check passed!
Gradient check passed!
Gradient check passed!


In [13]:
import utils
import config
importlib.reload(utils)
importlib.reload(config)

<module 'config' from 'C:\\Shahar\\BarIlan\\NLP-courses\\89687-DL\\Assignment1\\code\\config.py'>

In [107]:
a=utils.read_data(config.filename_dev)

In [109]:
a[:10]

[('it', '@_marrymezayn sì, perché non suoni abbastanza con lui çç (?)'),
 ('nl', 'sooo ik heb ook lang niet meer met @yordyadacruz getakkie'),
 ('es', 'desde arriba se ve todo mejor  http://t.co/cwogyapy'),
 ('de', 'lieder. erinnerungen. freude & wehmut.'),
 ('nl',
  '@debatop2 dat is tevens ook de kracht van het #cda dat het een middenpartij is, gewoon 1 cda houden dus!'),
 ('nl',
  'rt @tienerhumor_: beste gangsters, als jullie je broek eens omhoog zouden trekken zouden jullie harder weg kunnen rennen voor de politie ...'),
 ('it',
  '@klairehumanoid oddio mi dispiace, io ho visto mia madre per un periodo, per fortuna è passato'),
 ('de',
  '@yini78 das ist aber in ganz de so. im winter werden die gräber fast überall mit tanne abgedeckt. wohnst du in finsterwalde? :))'),
 ('nl', '@talkrih_hirtalk had het over mensen van me klas'),
 ('it', "ok prossima missione:comprare sorrisi e canzoni :')")]

In [110]:
utils.text_to_bigrams(a[0][1])

['@_',
 '_m',
 'ma',
 'ar',
 'rr',
 'ry',
 'ym',
 'me',
 'ez',
 'za',
 'ay',
 'yn',
 'n ',
 ' s',
 'sì',
 'ì,',
 ', ',
 ' p',
 'pe',
 'er',
 'rc',
 'ch',
 'hé',
 'é ',
 ' n',
 'no',
 'on',
 'n ',
 ' s',
 'su',
 'uo',
 'on',
 'ni',
 'i ',
 ' a',
 'ab',
 'bb',
 'ba',
 'as',
 'st',
 'ta',
 'an',
 'nz',
 'za',
 'a ',
 ' c',
 'co',
 'on',
 'n ',
 ' l',
 'lu',
 'ui',
 'i ',
 ' ç',
 'çç',
 'ç ',
 ' (',
 '(?',
 '?)']

In [117]:
from collections import Counter
f=Counter()
f.update(['a','b','c'])
f.update(['a','d','x'])
print(f)

Counter({'a': 2, 'b': 1, 'c': 1, 'd': 1, 'x': 1})


In [116]:
{i:x for i,x in enumerate(f)}

{0: 'a', 1: 'c', 2: 'x', 3: 'b', 4: 'd'}

In [119]:
{x:y for x,y in f.most_common(1)}

{'a': 2}

In [120]:
np.zeros(5, np.double)

array([0., 0., 0., 0., 0.])

In [212]:
import utils
import train_loglin as tl
import config
import loglinear as ll
importlib.reload(utils)
importlib.reload(tl)
importlib.reload(config)
importlib.reload(ll)

<module 'loglinear' from 'C:\\Shahar\\BarIlan\\NLP-courses\\89687-DL\\Assignment1\\code\\loglinear.py'>

In [213]:
train_data = utils.read_data(config.filename_train)
symbol_dict = tl.initialize_symbol_dict(train_data)
label_dict = tl.initialize_label_dict(train_data)
xy_train = list(tl.xy_generator(train_data, utils.text_to_bigrams, symbol_dict, label_dict))

dev_data = utils.read_data(config.filename_dev)
xy_dev = list(tl.xy_generator(dev_data, utils.text_to_bigrams, symbol_dict, label_dict))
in_dim = min(config.max_count, len(symbol_dict))
out_dim = len(label_dict)
print("problem dimensions are: {}".format((in_dim, out_dim)))


problem dimensions are: (600, 6)


In [214]:
params = ll.create_classifier(in_dim, out_dim)
trained_params = tl.train_classifier(xy_train, xy_dev, config.num_iterations, config.learning_rate, params)


yhat counter: Counter({4: 417, 3: 394, 5: 387, 0: 382, 1: 382, 2: 372})
yhat counter: Counter({2: 56, 1: 51, 3: 50, 4: 49, 0: 47, 5: 47})
I 0, train_loss [[0.177866]], train_accuracy 0.9451585261353899, dev_accuracy 0.8666666666666667, grads [[ 0.01268527 -0.16294542  0.00279707  0.12843345  0.00060814  0.01842149]]
yhat counter: Counter({0: 396, 3: 394, 1: 393, 2: 389, 5: 384, 4: 378})
yhat counter: Counter({1: 60, 2: 55, 0: 50, 3: 48, 5: 45, 4: 42})
I 1, train_loss [[0.17209816]], train_accuracy 0.967866323907455, dev_accuracy 0.8433333333333334, grads [[ 0.00601897  0.00272223  0.1094102   0.0261935   0.01375858 -0.15810347]]
yhat counter: Counter({5: 402, 3: 396, 4: 392, 0: 390, 2: 383, 1: 371})
yhat counter: Counter({2: 53, 5: 53, 1: 51, 3: 50, 0: 48, 4: 45})
I 2, train_loss [[0.02091245]], train_accuracy 0.9772922022279349, dev_accuracy 0.84, grads [[ 1.55871821e-06  6.76082927e-08  2.03227678e-02  2.96948030e-05
  -2.06953056e-02  3.41216600e-04]]
yhat counter: Counter({5: 408, 

In [205]:
type(grad)

numpy.matrixlib.defmatrix.matrix

In [134]:
x,y=next(xy)
print((x,y))

(array([2., 0., 0., 1., 0., 0., 0., 2., 2., 0., 0., 1., 1., 2., 0., 0., 1.,
       0., 0., 1., 0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 1., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       1., 1., 1., 0., 2., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0.,
       1., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 0., 2., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 3., 0., 0., 0., 0., 0.,
       1., 0., 0., 0., 2., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
       1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0

In [132]:
train_data[0]

('it', 'voglio cantare anche io: "celerino, figlio di putt**a!" (acab docet)')

In [135]:
np.where(x)

(array([  0,   3,   7,   8,  11,  12,  13,  16,  19,  22,  23,  25,  29,
         30,  31,  40,  46,  51,  52,  53,  55,  56,  60,  63,  68,  71,
         72,  84,  89,  97, 130, 136, 140, 147, 153, 169, 181, 185, 197,
        204, 265, 269, 286, 289, 300, 306, 335, 357, 393, 431], dtype=int64),)

In [143]:
[(k,v) for k,v in symbol_dict.items() if v in [  0,   3,   7,   8,  11,  12,  13,  16,  19,  22,  23,  25,  29, 54]]

[('e ', 0),
 ('er', 3),
 ('o ', 7),
 (' d', 8),
 ('in', 11),
 (' a', 12),
 ('an', 13),
 ('ch', 16),
 ('re', 19),
 (' c', 22),
 ('i ', 23),
 ('ar', 25),
 ('le', 29),
 ('se', 54)]

In [144]:
big_xy=list(xy)

In [145]:
len(big_xy)

2333

In [147]:
big_xy[1]

(array([2., 0., 0., 0., 0., 1., 3., 0., 1., 3., 3., 5., 0., 1., 1., 0., 1.,
        0., 1., 1., 0., 0., 0., 0., 1., 1., 0., 2., 0., 1., 0., 0., 0., 0.,
        1., 0., 1., 2., 3., 0., 0., 1., 0., 1., 0., 0., 0., 1., 1., 1., 2.,
        0., 0., 0., 0., 0., 0., 3., 0., 0., 0., 1., 0., 1., 2., 0., 0., 1.,
        0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0., 2., 2., 1., 0., 0.,
        0., 1., 0., 1., 0., 0., 3., 2., 0., 0., 0., 1., 0., 1., 1., 0., 0.,
        0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 1., 0., 0.,
        0., 0., 0., 2., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 

In [165]:
x=np.array([1., 2., 3.])

In [166]:
x


array([1., 2., 3.])

In [171]:
np.array(x,ndmin=2)

array([[1., 2., 3.]])

In [179]:
a=np.array([1,2,3])
b=np.array([4,5,6])
p=(a,b)

In [180]:
for t in p:
    t[2]=10

In [181]:
a

array([ 1,  2, 10])

In [182]:
b

array([ 4,  5, 10])

In [183]:
p


(array([ 1,  2, 10]), array([ 4,  5, 10]))

In [186]:
sum([True, True ,False])

2

#### testing mlp1.py

In [68]:
import mlp1
importlib.reload(mlp1)
import testing
importlib.reload(testing)
import loglinear as ll
importlib.reload(ll)

<module 'loglinear' from 'C:\\Shahar\\BarIlan\\NLP-courses\\89687-DL\\Assignment1\\code\\loglinear.py'>

In [26]:
W,b,U, b_tag = mlp1.create_classifier(12,4,6)


In [46]:
x = np.ones((1,12), np.double)
y = 4

In [56]:
W = testing.randomize_array(W)
b = testing.randomize_array(b)
U = testing.randomize_array(U)
b_tag = testing.randomize_array(b_tag)

In [57]:
y_e, y_hat, loss, y_diff = mlp1.loss_and_gradients(x,y,(W,b,U,b_tag))

In [58]:
print(y_e)
print(y_hat)
print(loss)
print(y_diff)

[[0. 0. 0. 0. 1. 0.]]
[[0.04327826 0.0152138  0.0089677  0.00102924 0.92939732 0.00211369]]
[[0.07321895]]
[[ 0.04327826  0.0152138   0.0089677   0.00102924 -0.07060268  0.00211369]]


In [51]:
ll.logloss(y, y_hat)

array([[7.16703788],
       [7.16703788],
       [7.16703788],
       [7.16703788],
       [7.16703788],
       [7.16703788]])

In [52]:
print(y)
print(y_hat)

4
[[0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]]


for small x, with W = I (the unit matrix) and b=0, we expect the result to be the same as for loglinear classifier


In [74]:
W,b,U, b_tag = mlp1.create_classifier(12,12,6)
W = np.eye(12)
x = np.random.rand(1,12)*0.1
U = testing.randomize_array(U)
b_tag = testing.randomize_array(b_tag)
loss2 = mlp1.loss_and_gradients(x,4,(W,b,U,b_tag))
loss1,_ = ll.loss_and_gradients(x,4,(U,b_tag))
print(loss1, loss2)

v1
loss: [[3.32499902]]
[[3.32521307]] [[3.32499902]]


In [78]:
1 - np.array([[1.,2.,3.]]) ** 2

array([[ 0., -3., -8.]])

#### now testing the gradient calculation

In [125]:
import testing
importlib.reload(testing)
import mlp1
importlib.reload(mlp1)
import loglinear as ll
importlib.reload(ll)
import grad_check
importlib.reload(grad_check)

<module 'grad_check' from 'C:\\Shahar\\BarIlan\\NLP-courses\\89687-DL\\Assignment1\\code\\grad_check.py'>

In [126]:
testing.mlp1_grad_sanity()

b_tag
Gradient check complete 
U:
Gradient check complete 
b:
Gradient check complete 
W:
Gradient check complete 
b_tag
Gradient check complete 
U:
Gradient check complete 
b:
Gradient check complete 
W:
Gradient check complete 
b_tag
Gradient check complete 
U:
Gradient check complete 
b:
Gradient check complete 
W:
Gradient check complete 
b_tag
Gradient check complete 
U:
Gradient check complete 
b:
Gradient check complete 
W:
Gradient check complete 
b_tag
Gradient check complete 
U:
Gradient check complete 
b:
Gradient check complete 
W:
Gradient check complete 
b_tag
Gradient check complete 
U:
Gradient check complete 
b:
Gradient check complete 
W:
Gradient check complete 
b_tag
Gradient check complete 
U:
Gradient check complete 
b:
Gradient check complete 
W:
Gradient check complete 
b_tag
Gradient check complete 
U:
Gradient check complete 
b:
Gradient check complete 
W:
Gradient check complete 
b_tag
Gradient check complete 
U:
Gradient check complete 
b:
Gradient check com

In [117]:
np.diag(np.array([-1000,1
                  ,1000]))

array([[-1000,     0,     0],
       [    0,     1,     0],
       [    0,     0,  1000]])

In [33]:
np.diag(np.squeeze(1- np.round(a[0]) ** 2))

array([[-15.,   0.,   0.,   0.,   0.,   0.],
       [  0., -48.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   1.,   0.,   0.],
       [  0.,   0.,   0.,   0., -63.,   0.],
       [  0.,   0.,   0.,   0.,   0., -15.]])

In [37]:
a

(array([[1.79175947]]), [array([[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]),
  array([[0., 0., 0., 0., 0., 0.]]),
  array([[ 0.82654857,  0.83329157, -0.83333315, -0.61660245, -0.8306838 ,
           0.11179183],
         [-0.16530971, -0.16665831,  0.16666663,  0.12332049,  0.16613676,
          -0.02235837],
         [-0.16530971, -0.16665831,  0.16666663,  0.12332049,  0.16613676,
          -0.02235837],
         [-0.16530971, -0.16665831,  0.16666663,  0.12332049,  0.16613676,
          -0.02235837],
         [-0.16530971, -0.16665831,  0.16666663,  0.12332049,  0.16613676,
          -0.02235837],
         [-0.16530971, -0.16665831,  0.16666663,  0.12332049,  0.16613676,
          -0.02235837]]),
  array([[-0.83333333,  0.16666667,  0.16666667,  0.16666667,  0.16666667,
           0.16666667]])])

In [18]:
next(a)

[[-3.58872272 -0.52344462 -1.6341967  -3.80449101  0.22498835 -5.66938495]]


StopIteration: (array([[-3.58872272, -0.52344462, -1.6341967 , -3.80449101,  0.22498835,
        -5.66938495]]), [0, 0])

In [98]:
np.tile(np.array([[1,2,3]]),(3,1))

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [11]:
next(z)

StopIteration: a

In [120]:
np.array([[1.,2.,3.]]) * np.array([[4.,5.,6.]])

array([[ 4., 10., 18.]])

#### training mlp1

In [160]:
import config
importlib.reload(config)
import train_loglin
importlib.reload(train_loglin)
import mlp1
importlib.reload(mlp1)
import train_mlp1
importlib.reload(train_mlp1)
trained_params = train_mlp1.main()


problem dimensions are: (600, 150, 6)
yhat counter: Counter({5: 433, 4: 423, 0: 391, 2: 373, 1: 364, 3: 350})
yhat counter: Counter({0: 59, 2: 58, 4: 53, 5: 51, 1: 46, 3: 33})
I 0, train_loss [[3.76904825]], train_accuracy 0.85690, dev_accuracy 0.71000
yhat counter: Counter({2: 430, 3: 413, 1: 400, 4: 394, 0: 349, 5: 348})
yhat counter: Counter({2: 61, 3: 58, 1: 49, 4: 48, 0: 43, 5: 41})
I 1, train_loss [[0.86920169]], train_accuracy 0.92502, dev_accuracy 0.72333
yhat counter: Counter({1: 400, 0: 399, 4: 392, 2: 389, 5: 378, 3: 376})
yhat counter: Counter({0: 62, 2: 58, 1: 51, 4: 49, 5: 43, 3: 37})
I 2, train_loss [[0.25449428]], train_accuracy 0.97943, dev_accuracy 0.74333
yhat counter: Counter({1: 394, 4: 392, 2: 391, 0: 389, 5: 385, 3: 383})
yhat counter: Counter({0: 61, 2: 53, 1: 53, 4: 47, 5: 46, 3: 40})
I 3, train_loss [[0.07514877]], train_accuracy 0.99786, dev_accuracy 0.75667
yhat counter: Counter({1: 395, 4: 393, 2: 389, 0: 389, 3: 384, 5: 384})
yhat counter: Counter({0: 58, 

In [161]:
codepath = 'C:\\Shahar\\BarIlan\\NLP-courses\\89687-DL\\Assignment1\\code'
from os import path
exec(open(path.join(codepath,'train_mlp1.py')).read())

problem dimensions are: (600, 150, 6)
yhat counter: Counter({0: 493, 2: 465, 5: 419, 1: 331, 4: 326, 3: 300})
yhat counter: Counter({0: 67, 5: 62, 2: 58, 4: 44, 1: 40, 3: 29})
I 0, train_loss [[4.35594434]], train_accuracy 0.82776, dev_accuracy 0.71333
yhat counter: Counter({5: 402, 1: 398, 3: 394, 4: 391, 2: 378, 0: 371})
yhat counter: Counter({5: 62, 4: 53, 0: 52, 1: 51, 2: 44, 3: 38})
I 1, train_loss [[0.80002854]], train_accuracy 0.94602, dev_accuracy 0.74333
yhat counter: Counter({2: 404, 0: 401, 4: 394, 5: 386, 1: 376, 3: 373})
yhat counter: Counter({4: 59, 0: 58, 5: 55, 2: 53, 1: 43, 3: 32})
I 2, train_loss [[0.28160941]], train_accuracy 0.97558, dev_accuracy 0.75333
yhat counter: Counter({1: 395, 4: 392, 2: 388, 5: 388, 0: 386, 3: 385})
yhat counter: Counter({5: 57, 4: 56, 0: 55, 1: 52, 2: 45, 3: 35})
I 3, train_loss [[0.07914927]], train_accuracy 0.99700, dev_accuracy 0.75667
yhat counter: Counter({1: 394, 4: 392, 2: 390, 0: 388, 3: 386, 5: 384})
yhat counter: Counter({0: 56, 

#### testing parts of mlpn

In [247]:
import mlpn
importlib.reload(mlpn)

<module 'mlpn' from 'C:\\Shahar\\BarIlan\\NLP-courses\\89687-DL\\Assignment1\\code\\mlpn.py'>

In [166]:
params = mlpn.create_classifier([5,6,7,8])

[(5, 6), (1, 6), (6, 7), (1, 7), (7, 8), (1, 8)]

In [172]:
params = mlpn.create_classifier([5,5,5,5])
[p.shape for p in params]

[(5, 5), (1, 5), (5, 5), (1, 5), (5, 5), (1, 5)]

In [176]:
params[::2]=[np.eye(5) for i in range(3)] 
[p.shape for p in params]

[(5, 5), (1, 5), (5, 5), (1, 5), (5, 5), (1, 5)]

###### test feedforward step

In [197]:
W=np.eye(5)
b=np.zeros((1,5))
a_in = np.array(np.arange(0,0.5,0.1), np.double, ndmin=2)

z,a_out = mlpn.layer_ff(a_in,(W,b),np.tanh)

print("a_in: {}\n z:{}\n a_out: {}".format(a_in, z, a_out))

a_in: [[0.  0.1 0.2 0.3 0.4]]
 z:[[0.  0.1 0.2 0.3 0.4]]
 a_out: [[0.         0.09966799 0.19737532 0.29131261 0.37994896]]


In [211]:
type(a_in)

numpy.ndarray

In [218]:
# this tests the feedforward code by building a 
# network of 3 identity (eye matrix) hidden layers
x = np.random.randn(5)*0.1
print("x: {}, \nsoftmax: {}".format(x, ll.softmax(x)))

y = mlpn.feedforward_loop(x, params)

for i, az in enumerate(y):
    a, z = az
    print("{}\na:\n{}\nz:\n{}".format(i,a,z))
[(t[0].shape, t[1].shape) for t in y]

x: [ 0.22510243 -0.07632781  0.14063318 -0.02407293 -0.05131847], 
softmax: [0.23828267 0.17627186 0.21898176 0.18572783 0.18073589]
0
a:
[[ 0.22510243 -0.07632781  0.14063318 -0.02407293 -0.05131847]]
z:
[[ 0.22137588 -0.07617993  0.13971332 -0.02406828 -0.05127346]]
1
a:
[[ 0.22137588 -0.07617993  0.13971332 -0.02406828 -0.05127346]]
z:
[[ 0.21782905 -0.0760329   0.1388113  -0.02406363 -0.05122858]]
2
a:
[[ 0.21782905 -0.0760329   0.1388113  -0.02406363 -0.05122858]]
z:
[[0.23704307 0.17668702 0.21903338 0.1861121  0.18112443]]


[((1, 5), (1, 5)), ((1, 5), (1, 5)), ((1, 5), (1, 5))]

In [221]:
# after seeing the whole feedforward progression, let's check the 
# small function that gets x and returns the final a
mlpn.classifier_output(x,params)

array([[0.23704307, 0.17668702, 0.21903338, 0.1861121 , 0.18112443]])

##### testing the backpropagation

In [225]:
mlpn.classifier_output(np.array([[1.,0.,0.,0.,0.]]),params)

array([[0.32206907, 0.16948273, 0.16948273, 0.16948273, 0.16948273]])

In [249]:
mlpn.loss_and_gradients(np.array([[1.,1.,0.,0.,0.]]),0,params)    

len z_and_a: 4
layer: 3
layer: 1


(array([[1.27499765]]),
 [array([[-0.42649373,  0.16539143,  0.0923642 ,  0.0923642 ,  0.0923642 ],
         [-0.42649373,  0.16539143,  0.0923642 ,  0.0923642 ,  0.0923642 ],
         [-0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
         [-0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
         [-0.        ,  0.        ,  0.        ,  0.        ,  0.        ]]),
  array([[-0.66430493,  0.25761303,  0.1438661 ,  0.1438661 ,  0.1438661 ]]),
  array([[-0.27899103,  0.10819086,  0.1438661 ,  0.1438661 ,  0.1438661 ],
         [-0.27899103,  0.10819086,  0.1438661 ,  0.1438661 ,  0.1438661 ],
         [-0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
         [-0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
         [-0.        ,  0.        ,  0.        ,  0.        ,  0.        ]]),
  array([[-0.27899103,  0.10819086,  0.1438661 ,  0.1438661 ,  0.1438661 ]])])

In [250]:
len

AttributeError: 'list' object has no attribute '__length__'