In [1]:
import torch
import torch.nn as nn

In [7]:
lst = nn.LSTM(input_size=10,hidden_size=7,num_layers=2)

In [15]:
h1=torch.zeros(2,1,7)
c1 = torch.zeros(2,1,7)
inp1 = torch.zeros(10)

In [16]:
lst(inp1.view(1,1,10),(h1,c1))

(tensor([[[ 0.0182, -0.0071, -0.0539, -0.1354, -0.1810, -0.0242,  0.0352]]],
        grad_fn=<StackBackward>),
 (tensor([[[ 0.0879, -0.0532,  0.0011, -0.0076,  0.0607,  0.0591,  0.0433]],
  
          [[ 0.0182, -0.0071, -0.0539, -0.1354, -0.1810, -0.0242,  0.0352]]],
         grad_fn=<StackBackward>),
  tensor([[[ 0.1734, -0.1076,  0.0026, -0.0126,  0.1419,  0.1131,  0.1039]],
  
          [[ 0.0360, -0.0135, -0.1093, -0.2361, -0.2879, -0.0679,  0.0791]]],
         grad_fn=<StackBackward>)))

In [26]:
a =torch.cat([torch.randn(1,1,7), torch.randn(1,1,7)])

In [27]:
a

tensor([[[-0.1422, -0.3848,  0.2625, -0.0748,  0.5658,  0.0145,  0.2287]],

        [[ 0.1479,  0.2877, -0.8007,  0.0406,  2.0156, -0.6418,  0.6649]]])

In [28]:

a[0,:,:]

tensor([[-0.1422, -0.3848,  0.2625, -0.0748,  0.5658,  0.0145,  0.2287]])

In [29]:
a[1,:,:]

tensor([[ 0.1479,  0.2877, -0.8007,  0.0406,  2.0156, -0.6418,  0.6649]])