In [1]:
import importlib
import numpy as np

In [2]:
# reload method is important when making changes in the code in the file.
import testing
importlib.reload(testing)
import loglinear
importlib.reload(loglinear)
import grad_check
importlib.reload(grad_check)
import config
importlib.reload(config)
import utils
importlib.reload(utils)
""

''

#### part 1 running the grad_check sanity


In [3]:
grad_check.sanity_check()

Running sanity checks...
Gradient check passed!
Gradient check passed!
Gradient check passed!



#### part 2 running the built-in sanity checks in loglinear.py 

In [4]:
exec(open('loglinear.py').read())

[0.26894142 0.73105858]
[0.26894142 0.73105858]
[0.73105858 0.26894142]
Gradient check passed!
Gradient check passed!
Gradient check passed!
Gradient check passed!
Gradient check passed!
Gradient check passed!
Gradient check passed!
Gradient check passed!
Gradient check passed!
Gradient check passed!
Gradient check passed!
Gradient check passed!
Gradient check passed!
Gradient check passed!
Gradient check passed!
Gradient check passed!
Gradient check passed!
Gradient check passed!
Gradient check passed!
Gradient check passed!


#### part3 training loglinear

In [5]:
exec(open('train_loglin.py').read())

problem dimensions are: (600, 6)
I 0, train_loss [[0.17891951]], train_accuracy 0.9305912596401028, dev_accuracy 0.8133333333333334
I 1, train_loss [[9.04813415e-05]], train_accuracy 0.9481576692373608, dev_accuracy 0.8266666666666667
I 2, train_loss [[2.25421622]], train_accuracy 0.9764353041988003, dev_accuracy 0.8566666666666667
I 3, train_loss [[0.0001498]], train_accuracy 0.9858611825192802, dev_accuracy 0.8433333333333334
I 4, train_loss [[0.00053345]], train_accuracy 0.9880034275921166, dev_accuracy 0.83
I 5, train_loss [[1.93852199e-07]], train_accuracy 0.9948586118251928, dev_accuracy 0.8466666666666667
early stopping criterion in iteration 6 - detriorating dev accuracy
top 7 scores for each language:
language: ['en'] bigrams: [('t ', 0.87), (' w', 0.98), ('y ', 1.26), ('d ', 1.01), ('th', 1.42), ('yo', 0.87), ('gh', 0.82)]
language: ['fr'] bigrams: [(' p', 1.01), ('ou', 1.71), ('ai', 1.25), ('oi', 1.4), (' !', 1.28), ("'e", 1.08), ('@t', 0.96)]
language: ['de'] bigrams: [('ch

#### part 4 predict on test
we run the loglin training again this time with a configuration telling it to use the trained classifier to predict.

The parameter is changed in config.py

In [6]:
importlib.reload(config)
exec(open('train_loglin.py').read())

problem dimensions are: (600, 6)
I 0, train_loss [[2.11719496]], train_accuracy 0.9288774635818338, dev_accuracy 0.8366666666666667
I 1, train_loss [[4.50950004e-06]], train_accuracy 0.9661525278491859, dev_accuracy 0.84
I 2, train_loss [[9.24740084e-06]], train_accuracy 0.9768637532133676, dev_accuracy 0.84
I 3, train_loss [[7.03319671e-07]], train_accuracy 0.9880034275921166, dev_accuracy 0.84
I 4, train_loss [[6.22528629e-05]], train_accuracy 0.9927163667523564, dev_accuracy 0.8366666666666667
I 5, train_loss [[1.37914287e-05]], train_accuracy 0.9944301628106256, dev_accuracy 0.84
I 6, train_loss [[0.00202802]], train_accuracy 0.9974293059125964, dev_accuracy 0.8533333333333334
early stopping criterion in iteration 7 - detriorating dev accuracy
top 7 scores for each language:
language: ['en'] bigrams: [('t ', 0.78), (' w', 1.07), ('y ', 1.27), ('d ', 1.02), ('th', 1.49), ('yo', 0.81), ('gh', 0.81)]
language: ['fr'] bigrams: [(' p', 1.06), ('ou', 1.76), ('ai', 1.37), ('oi', 1.41), ('

#### part 5 mlp with 1 hidden layer

In [7]:
# testing the gradients
import mlp1

testing.mlp1_grad_sanity()

b_tag
Gradient check passed!
U:
Gradient check passed!
b:
Gradient check passed!
W:
Gradient check passed!
b_tag
Gradient check passed!
U:
Gradient check passed!
b:
Gradient check passed!
W:
Gradient check passed!
b_tag
Gradient check passed!
U:
Gradient check passed!
b:
Gradient check passed!
W:
Gradient check passed!
b_tag
Gradient check passed!
U:
Gradient check passed!
b:
Gradient check passed!
W:
Gradient check passed!
b_tag
Gradient check passed!
U:
Gradient check passed!
b:
Gradient check passed!
W:
Gradient check passed!
b_tag
Gradient check passed!
U:
Gradient check passed!
b:
Gradient check passed!
W:
Gradient check passed!
b_tag
Gradient check passed!
U:
Gradient check passed!
b:
Gradient check passed!
W:
Gradient check passed!
b_tag
Gradient check passed!
U:
Gradient check passed!
b:
Gradient check passed!
W:
Gradient check passed!
b_tag
Gradient check passed!
U:
Gradient check passed!
b:
Gradient check passed!
W:
Gradient check passed!
b_tag
Gradient check passed!
U:
Gradi

##### unigrams - with a hidden layer

In [8]:
import train_mlp1 as tp1
importlib.reload(tp1)
import utils
importlib.reload(utils)
import train_loglin as tl
importlib.reload(tl)
importlib.reload(config)

<module 'config' from 'C:\\Shahar\\BarIlan\\NLP-courses\\89687-DL\\Assignment1\\code\\config.py'>

In [10]:
trained_mlp1_unigrams = tp1.main(utils.text_to_unigrams)

problem dimensions are: (129, 150, 6)
I 0, train_loss [[4.88007762]], train_accuracy 0.40616966580976865, dev_accuracy 0.35333333333333333
I 1, train_loss [[2.53203296]], train_accuracy 0.5115681233933161, dev_accuracy 0.37666666666666665
I 2, train_loss [[1.98302262]], train_accuracy 0.5535561268209083, dev_accuracy 0.38
I 3, train_loss [[1.69921712]], train_accuracy 0.5689802913453299, dev_accuracy 0.3933333333333333
I 4, train_loss [[1.42861048]], train_accuracy 0.6143958868894601, dev_accuracy 0.47
I 5, train_loss [[1.28222901]], train_accuracy 0.6165381319622965, dev_accuracy 0.4866666666666667
I 6, train_loss [[1.15079935]], train_accuracy 0.6713796058269066, dev_accuracy 0.43333333333333335
I 7, train_loss [[1.0900732]], train_accuracy 0.6996572407883462, dev_accuracy 0.49333333333333335
I 8, train_loss [[1.00169389]], train_accuracy 0.6885175664095973, dev_accuracy 0.43333333333333335
I 9, train_loss [[0.96635827]], train_accuracy 0.6975149957155099, dev_accuracy 0.49
I 10, tra

##### unigrams - linear classifier

In [9]:
importlib.reload(tl)
importlib.reload(config)
trained_ll_unigrams = tl.main(utils.text_to_unigrams)

problem dimensions are: (129, 6)
I 0, train_loss [[1.879717e-07]], train_accuracy 0.6379605826906598, dev_accuracy 0.5533333333333333
I 1, train_loss [[1.22524152e-05]], train_accuracy 0.6893744644387317, dev_accuracy 0.6233333333333333
I 2, train_loss [[21.20900202]], train_accuracy 0.6328191945158527, dev_accuracy 0.5866666666666667
I 3, train_loss [[5.82453761]], train_accuracy 0.517566409597258, dev_accuracy 0.49
I 4, train_loss [[4.74815964e-10]], train_accuracy 0.7125107112253641, dev_accuracy 0.6166666666666667
I 5, train_loss [[16.33163482]], train_accuracy 0.6015424164524421, dev_accuracy 0.5666666666666667
I 6, train_loss [[-0.]], train_accuracy 0.6718080548414739, dev_accuracy 0.6166666666666667
I 7, train_loss [[2.10942375e-15]], train_accuracy 0.7703513281919452, dev_accuracy 0.69
early stopping criterion in iteration 8 - detriorating dev accuracy
top 7 scores for each language:
language: ['en'] bigrams: [('t', 3.38), ('h', 2.92), ('g', 3.05), ('f', 2.95), ('w', 6.07), ('y

##### scoring on the dev set for mlp1

In [11]:
exec(open('train_mlp1.py').read())

problem dimensions are: (600, 150, 6)
I 0, train_loss [[7.96857676]], train_accuracy 0.6473864610111397, dev_accuracy 0.5266666666666666
I 1, train_loss [[2.72974294]], train_accuracy 0.7896315338474722, dev_accuracy 0.5733333333333334
I 2, train_loss [[1.45139192]], train_accuracy 0.8671808054841473, dev_accuracy 0.62
I 3, train_loss [[0.89275097]], train_accuracy 0.9143101970865467, dev_accuracy 0.6033333333333334
I 4, train_loss [[0.59048195]], train_accuracy 0.9370179948586118, dev_accuracy 0.6133333333333333
I 5, train_loss [[0.41724797]], train_accuracy 0.9528706083976007, dev_accuracy 0.6133333333333333
I 6, train_loss [[0.30143384]], train_accuracy 0.9665809768637532, dev_accuracy 0.6066666666666667
I 7, train_loss [[0.22076562]], train_accuracy 0.9764353041988003, dev_accuracy 0.6066666666666667
I 8, train_loss [[0.16647898]], train_accuracy 0.9828620394173093, dev_accuracy 0.6066666666666667
I 9, train_loss [[0.12641758]], train_accuracy 0.9880034275921166, dev_accuracy 0.61


##### learn xor with mlp1

In [12]:
importlib.reload(tp1)
importlib.reload(mlp1)

<module 'mlp1' from 'C:\\Shahar\\BarIlan\\NLP-courses\\89687-DL\\Assignment1\\code\\mlp1.py'>

In [13]:
params = mlp1.create_classifier(2,2,2)
for i,p in enumerate(params):
    print("{}:\n{}".format(i,p))

0:
[[0. 0.]
 [0. 0.]]
1:
[[0. 0.]]
2:
[[0. 0.]
 [0. 0.]]
3:
[[0. 0.]]


In [14]:
xor_data = [(0,[0,0]),
        (1,[0,1]),
        (1,[1,0]),
        (0,[1,1])]

xor_data1 = [(np.array(b,np.double),a) for a, b in xor_data]
    
print(xor_data1)


[(array([0., 0.]), 0), (array([0., 1.]), 1), (array([1., 0.]), 1), (array([1., 1.]), 0)]


In [ ]:
print(params)
for x,_ in xor_data1:
    print(x)
    print(mlp1.classifier_output(x,params))
    print(mlp1.predict(x, params))

In [ ]:
# random initialization, 8 nodes in hidden layer - find a solution after 15 iterations
params = mlp1.create_classifier(2,8,2)
params= [tp1.randomize_array(p) for p in params]
tp1.train_classifier(xor_data1,xor_data1, 50, 0.03, params)

In [17]:
# with a 'good' initialization, finds a solution with hidden layer of 2
params = mlp1.create_classifier(2,2,2)
params[0] = np.array([[1, -2],[-2,1]],np.double)
params[2] = np.array([[1,0],[0,1]],np.double)
tp1.train_classifier(xor_data1,xor_data1, 50, 0.1, params)

I 0, train_loss [[0.91097259]], train_accuracy 0.75, dev_accuracy 0.75
I 1, train_loss [[0.85803015]], train_accuracy 0.75, dev_accuracy 0.75
I 2, train_loss [[0.81684644]], train_accuracy 0.75, dev_accuracy 0.75
I 3, train_loss [[0.78326454]], train_accuracy 0.75, dev_accuracy 0.75
I 4, train_loss [[0.75738499]], train_accuracy 0.75, dev_accuracy 0.75
I 5, train_loss [[0.73881007]], train_accuracy 0.75, dev_accuracy 0.75
I 6, train_loss [[0.72431747]], train_accuracy 0.75, dev_accuracy 0.75
I 7, train_loss [[0.71004397]], train_accuracy 0.75, dev_accuracy 0.75
I 8, train_loss [[0.69647024]], train_accuracy 0.75, dev_accuracy 0.75
I 9, train_loss [[0.68549179]], train_accuracy 0.75, dev_accuracy 0.75
I 10, train_loss [[0.6758219]], train_accuracy 0.75, dev_accuracy 0.75
I 11, train_loss [[0.66825408]], train_accuracy 0.75, dev_accuracy 0.75
I 12, train_loss [[0.66006524]], train_accuracy 0.75, dev_accuracy 0.75
I 13, train_loss [[0.64937837]], train_accuracy 0.5, dev_accuracy 0.5
I 14,

[array([[ 1.64141557, -2.29104753],
        [-2.16084151,  1.90681595]]),
 array([[-0.68092726, -0.90957932]]),
 array([[-0.56410602,  1.56410602],
        [-0.61443532,  1.61443532]]),
 array([[-0.82614701,  0.82614701]])]

In [15]:
# again random initialization, 8 nodes in hidden layer - this time took 28 iterations
params = mlp1.create_classifier(2,8,2)
params= [tp1.randomize_array(p) for p in params]
tp1.train_classifier(xor_data1,xor_data1, 50, 0.03, params)

I 0, train_loss [[0.96049661]], train_accuracy 0.5, dev_accuracy 0.5
I 1, train_loss [[0.90442097]], train_accuracy 0.5, dev_accuracy 0.5
I 2, train_loss [[0.86586643]], train_accuracy 0.5, dev_accuracy 0.5
I 3, train_loss [[0.84398623]], train_accuracy 0.5, dev_accuracy 0.5
I 4, train_loss [[0.82116887]], train_accuracy 0.25, dev_accuracy 0.25
I 5, train_loss [[0.81089389]], train_accuracy 0.5, dev_accuracy 0.5
I 6, train_loss [[0.79995025]], train_accuracy 0.5, dev_accuracy 0.5
I 7, train_loss [[0.79300897]], train_accuracy 0.5, dev_accuracy 0.5
I 8, train_loss [[0.78330701]], train_accuracy 0.5, dev_accuracy 0.5
I 9, train_loss [[0.77487947]], train_accuracy 0.5, dev_accuracy 0.5
I 10, train_loss [[0.76822765]], train_accuracy 0.5, dev_accuracy 0.5
I 11, train_loss [[0.76490518]], train_accuracy 0.5, dev_accuracy 0.5
I 12, train_loss [[0.75536163]], train_accuracy 0.5, dev_accuracy 0.5
I 13, train_loss [[0.75271855]], train_accuracy 0.75, dev_accuracy 0.75
I 14, train_loss [[0.74596

[array([[ 1.76057624e+00,  4.78677944e-01,  2.63068427e-01,
          9.92861108e-01, -2.69357639e-01,  1.28070140e-01,
         -2.04608949e-01,  4.58013774e-01],
        [-7.85487620e-01,  1.83888434e+00,  7.95579307e-02,
         -3.15583678e-04,  1.42987036e+00,  1.53001930e+00,
          1.67873895e+00,  1.50410214e+00]]),
 array([[ 0.84535847,  0.23292762, -1.69283007, -0.53933251,  0.25679858,
         -0.68579516,  0.41124505,  1.21933082]]),
 array([[ 0.4578094 , -1.26532268],
        [-0.17767124,  1.12198156],
        [-0.16764888,  0.89152872],
        [ 0.25453609,  0.43856957],
        [ 1.00914608, -0.00437015],
        [ 1.41649183,  1.54009867],
        [-0.69262088, -1.67262992],
        [ 0.31119953,  0.68099009]]),
 array([[-0.33199024,  1.6501879 ]])]

In [18]:
# random initialization, 2 nodes in hidden layer - not there even after 500 iterations
params = mlp1.create_classifier(2,2,2)
params= [tp1.randomize_array(p) for p in params]
tp1.train_classifier(xor_data1,xor_data1, 500, 0.03, params)

I 0, train_loss [[0.80739901]], train_accuracy 0.5, dev_accuracy 0.5
I 1, train_loss [[0.80355084]], train_accuracy 0.5, dev_accuracy 0.5
I 2, train_loss [[0.78631474]], train_accuracy 0.5, dev_accuracy 0.5
I 3, train_loss [[0.78767239]], train_accuracy 0.5, dev_accuracy 0.5
I 4, train_loss [[0.77232216]], train_accuracy 0.5, dev_accuracy 0.5
I 5, train_loss [[0.77719822]], train_accuracy 0.5, dev_accuracy 0.5
I 6, train_loss [[0.76427627]], train_accuracy 0.5, dev_accuracy 0.5
I 7, train_loss [[0.76645912]], train_accuracy 0.5, dev_accuracy 0.5
I 8, train_loss [[0.75804957]], train_accuracy 0.5, dev_accuracy 0.5
I 9, train_loss [[0.7599244]], train_accuracy 0.5, dev_accuracy 0.5
I 10, train_loss [[0.75710692]], train_accuracy 0.5, dev_accuracy 0.5
I 11, train_loss [[0.75103159]], train_accuracy 0.5, dev_accuracy 0.5
I 12, train_loss [[0.75302866]], train_accuracy 0.5, dev_accuracy 0.5
I 13, train_loss [[0.74981731]], train_accuracy 0.5, dev_accuracy 0.5
I 14, train_loss [[0.74859647]]

I 124, train_loss [[0.66153253]], train_accuracy 0.5, dev_accuracy 0.5
I 125, train_loss [[0.660258]], train_accuracy 0.5, dev_accuracy 0.5
I 126, train_loss [[0.65949472]], train_accuracy 0.5, dev_accuracy 0.5
I 127, train_loss [[0.65608766]], train_accuracy 0.5, dev_accuracy 0.5
I 128, train_loss [[0.65672687]], train_accuracy 0.5, dev_accuracy 0.5
I 129, train_loss [[0.65716845]], train_accuracy 0.5, dev_accuracy 0.5
I 130, train_loss [[0.65390332]], train_accuracy 0.5, dev_accuracy 0.5
I 131, train_loss [[0.65490094]], train_accuracy 0.5, dev_accuracy 0.5
I 132, train_loss [[0.65358395]], train_accuracy 0.5, dev_accuracy 0.5
I 133, train_loss [[0.65156682]], train_accuracy 0.5, dev_accuracy 0.5
I 134, train_loss [[0.65120215]], train_accuracy 0.5, dev_accuracy 0.5
I 135, train_loss [[0.65054015]], train_accuracy 0.5, dev_accuracy 0.5
I 136, train_loss [[0.64935323]], train_accuracy 0.5, dev_accuracy 0.5
I 137, train_loss [[0.6478244]], train_accuracy 0.5, dev_accuracy 0.5
I 138, tr

I 258, train_loss [[0.51660234]], train_accuracy 0.5, dev_accuracy 0.5
I 259, train_loss [[0.51564548]], train_accuracy 0.5, dev_accuracy 0.5
I 260, train_loss [[0.51482043]], train_accuracy 0.5, dev_accuracy 0.5
I 261, train_loss [[0.51371678]], train_accuracy 0.5, dev_accuracy 0.5
I 262, train_loss [[0.51317732]], train_accuracy 0.5, dev_accuracy 0.5
I 263, train_loss [[0.51226493]], train_accuracy 0.5, dev_accuracy 0.5
I 264, train_loss [[0.51151016]], train_accuracy 0.5, dev_accuracy 0.5
I 265, train_loss [[0.5107141]], train_accuracy 0.5, dev_accuracy 0.5
I 266, train_loss [[0.50989371]], train_accuracy 0.5, dev_accuracy 0.5
I 267, train_loss [[0.50906131]], train_accuracy 0.5, dev_accuracy 0.5
I 268, train_loss [[0.50779152]], train_accuracy 0.5, dev_accuracy 0.5
I 269, train_loss [[0.50744347]], train_accuracy 0.5, dev_accuracy 0.5
I 270, train_loss [[0.5061807]], train_accuracy 0.5, dev_accuracy 0.5
I 271, train_loss [[0.50598113]], train_accuracy 0.5, dev_accuracy 0.5
I 272, t

I 396, train_loss [[0.44159526]], train_accuracy 0.5, dev_accuracy 0.5
I 397, train_loss [[0.44130603]], train_accuracy 0.5, dev_accuracy 0.5
I 398, train_loss [[0.44100044]], train_accuracy 0.5, dev_accuracy 0.5
I 399, train_loss [[0.44082818]], train_accuracy 0.5, dev_accuracy 0.5
I 400, train_loss [[0.44049336]], train_accuracy 0.5, dev_accuracy 0.5
I 401, train_loss [[0.44017632]], train_accuracy 0.5, dev_accuracy 0.5
I 402, train_loss [[0.43986422]], train_accuracy 0.5, dev_accuracy 0.5
I 403, train_loss [[0.43954495]], train_accuracy 0.5, dev_accuracy 0.5
I 404, train_loss [[0.43925639]], train_accuracy 0.5, dev_accuracy 0.5
I 405, train_loss [[0.43891488]], train_accuracy 0.5, dev_accuracy 0.5
I 406, train_loss [[0.43865277]], train_accuracy 0.5, dev_accuracy 0.5
I 407, train_loss [[0.43837622]], train_accuracy 0.5, dev_accuracy 0.5
I 408, train_loss [[0.43807798]], train_accuracy 0.5, dev_accuracy 0.5
I 409, train_loss [[0.43768629]], train_accuracy 0.5, dev_accuracy 0.5
I 410,

[array([[ 1.38068544,  0.96052247],
        [-2.22540305,  2.05276525]]),
 array([[ 1.85914112, -2.87962314]]),
 array([[ 2.31210967, -0.60227861],
        [ 1.98673521, -1.25847457]]),
 array([[ 0.31655904, -0.01318184]])]

In [16]:
# with the right initialization, find a solution with 2 nodes in hidden layer 
params = mlp1.create_classifier(2,2,2)
params[0] = np.array([[-2, 0],[8,-2]],np.double)
params[2] = np.array([[1, 0],[0,1]],np.double)

params= [tp1.randomize_array(p) for p in params]
tp1.train_classifier(xor_data1,xor_data1, 60, 0.08, params)

I 0, train_loss [[0.75973056]], train_accuracy 0.5, dev_accuracy 0.5
I 1, train_loss [[0.74550738]], train_accuracy 0.5, dev_accuracy 0.5
I 2, train_loss [[0.7388596]], train_accuracy 0.5, dev_accuracy 0.5
I 3, train_loss [[0.7349417]], train_accuracy 0.5, dev_accuracy 0.5
I 4, train_loss [[0.7329532]], train_accuracy 0.5, dev_accuracy 0.5
I 5, train_loss [[0.73106988]], train_accuracy 0.5, dev_accuracy 0.5
I 6, train_loss [[0.72731061]], train_accuracy 0.5, dev_accuracy 0.5
I 7, train_loss [[0.72626716]], train_accuracy 0.5, dev_accuracy 0.5
I 8, train_loss [[0.72619806]], train_accuracy 0.5, dev_accuracy 0.5
I 9, train_loss [[0.72555089]], train_accuracy 0.5, dev_accuracy 0.5
I 10, train_loss [[0.72665514]], train_accuracy 0.5, dev_accuracy 0.5
I 11, train_loss [[0.72598342]], train_accuracy 0.5, dev_accuracy 0.5
I 12, train_loss [[0.72559264]], train_accuracy 0.5, dev_accuracy 0.5
I 13, train_loss [[0.72515167]], train_accuracy 0.5, dev_accuracy 0.5
I 14, train_loss [[0.72285251]], 

[array([[ 0.62522411, -0.74749971],
        [-0.65617709,  0.63622734]]),
 array([[0.59786162, 0.63944826]]),
 array([[-0.20254221, -0.71940079],
        [ 0.39711053, -0.15536803]]),
 array([[0.03159653, 0.44000234]])]