In [1]:
import importlib
import numpy as np

In [110]:
# reload method is important when making changes in the code in the file.
import testing
importlib.reload(testing)
import loglinear
importlib.reload(loglinear)
import grad_check
importlib.reload(grad_check)
import config
importlib.reload(config)
import utils
importlib.reload(utils)
""

''

#### part 1 running the grad_check sanity


In [158]:
grad_check.sanity_check()

Running sanity checks...
Gradient check passed!
Gradient check passed!
Gradient check passed!



#### part 2 running the built-in sanity checks in loglinear.py 

In [159]:
exec(open('loglinear.py').read())

[0.26894142 0.73105858]
[0.26894142 0.73105858]
[0.73105858 0.26894142]
Gradient check passed!
Gradient check passed!
Gradient check passed!
Gradient check passed!
Gradient check passed!
Gradient check passed!
Gradient check passed!
Gradient check passed!
Gradient check passed!
Gradient check passed!
Gradient check passed!
Gradient check passed!
Gradient check passed!
Gradient check passed!
Gradient check passed!
Gradient check passed!
Gradient check passed!
Gradient check passed!
Gradient check passed!
Gradient check passed!


#### part3 training loglinear

In [111]:
exec(open('train_loglin.py').read())

problem dimensions are: (600, 6)
I 0, train_loss [[0.74726506]], train_accuracy 0.9031705227077977, dev_accuracy 0.8033333333333333
I 1, train_loss [[0.02770769]], train_accuracy 0.9562982005141388, dev_accuracy 0.8566666666666667
I 2, train_loss [[0.05783995]], train_accuracy 0.9802913453299057, dev_accuracy 0.8566666666666667
I 3, train_loss [[0.02761137]], train_accuracy 0.9892887746358183, dev_accuracy 0.85
I 4, train_loss [[0.05970852]], train_accuracy 0.991859468723222, dev_accuracy 0.8633333333333333
I 5, train_loss [[3.76098486e-10]], train_accuracy 0.9948586118251928, dev_accuracy 0.8433333333333334
I 6, train_loss [[0.00493217]], train_accuracy 0.9970008568980291, dev_accuracy 0.85
I 7, train_loss [[0.03700755]], train_accuracy 0.9974293059125964, dev_accuracy 0.8566666666666667
I 8, train_loss [[8.76714036e-08]], train_accuracy 0.9978577549271637, dev_accuracy 0.86
early stopping criterion in iteration 9 - detriorating dev accuracy
top 7 scores for each language:
language: [

#### part 4 predict on test
we run the loglin training again this time with a configuration telling it to use the trained classifier to predict.

The parameter is changed in config.py

In [180]:
importlib.reload(config)
exec(open('train_loglin.py').read())

problem dimensions are: (600, 6)
I 0, train_loss [[4.53112961e-05]], train_accuracy 0.9383033419023136, dev_accuracy 0.8333333333333334
I 1, train_loss [[0.25884538]], train_accuracy 0.9695801199657241, dev_accuracy 0.85
I 2, train_loss [[1.9532776e-07]], train_accuracy 0.9781491002570694, dev_accuracy 0.84
I 3, train_loss [[0.04347014]], train_accuracy 0.988860325621251, dev_accuracy 0.8433333333333334
I 4, train_loss [[1.3396129]], train_accuracy 0.9862896315338475, dev_accuracy 0.8333333333333334
I 5, train_loss [[1.34849959e-05]], train_accuracy 0.9948586118251928, dev_accuracy 0.85
early stopping criterion in iteration 6 - detriorating dev accuracy
top 7 scores for each language:
language: ['it'] bigrams: [('o ', 1.31), ('i ', 1.23), ('ss', 0.93), ('gi', 1.02), ('uo', 0.85), ('e!', 0.84), ('@g', 0.85)]
language: ['nl'] bigrams: [('ee', 1.36), ('oo', 0.97), ('g ', 1.02), ('je', 0.93), ('oe', 1.35), ('ij', 1.53), ('zo', 0.91)]
language: ['en'] bigrams: [('t ', 0.79), (' w', 0.98), (

#### part 5 mlp with 1 hidden layer

In [157]:
# testing the gradients
import mlp1

testing.mlp1_grad_sanity()

b_tag
Gradient check passed!
U:
Gradient check passed!
b:
Gradient check passed!
W:
Gradient check passed!
b_tag
Gradient check passed!
U:
Gradient check passed!
b:
Gradient check passed!
W:
Gradient check passed!
b_tag
Gradient check passed!
U:
Gradient check passed!
b:
Gradient check passed!
W:
Gradient check passed!
b_tag
Gradient check passed!
U:
Gradient check passed!
b:
Gradient check passed!
W:
Gradient check passed!
b_tag
Gradient check passed!
U:
Gradient check passed!
b:
Gradient check passed!
W:
Gradient check passed!
b_tag
Gradient check passed!
U:
Gradient check passed!
b:
Gradient check passed!
W:
Gradient check passed!
b_tag
Gradient check passed!
U:
Gradient check passed!
b:
Gradient check passed!
W:
Gradient check passed!
b_tag
Gradient check passed!
U:
Gradient check passed!
b:
Gradient check passed!
W:
Gradient check passed!
b_tag
Gradient check passed!
U:
Gradient check passed!
b:
Gradient check passed!
W:
Gradient check passed!
b_tag
Gradient check passed!
U:
Gradi

##### unigrams - with a hidden layer

In [199]:
import train_mlp1 as tp1
importlib.reload(tp1)
import utils
importlib.reload(utils)
import train_loglin as tl
importlib.reload(tl)
importlib.reload(config)

<module 'config' from 'C:\\Shahar\\BarIlan\\NLP-courses\\89687-DL\\Assignment1\\code\\config.py'>

In [198]:
trained_mlp1_unigrams = tp1.main(utils.text_to_unigrams)

problem dimensions are: (129, 150, 6)
yhat counter: Counter({2: 514, 0: 511, 1: 403, 4: 332, 5: 294, 3: 280})
yhat counter: Counter({2: 74, 1: 58, 0: 52, 3: 40, 4: 39, 5: 37})
I 0, train_loss [[4.51124267]], train_accuracy 0.4254498714652956, dev_accuracy 0.33666666666666667
yhat counter: Counter({1: 584, 3: 575, 2: 405, 5: 289, 4: 249, 0: 232})
yhat counter: Counter({3: 82, 1: 77, 2: 55, 5: 43, 0: 22, 4: 21})
I 1, train_loss [[2.46582505]], train_accuracy 0.46872322193658955, dev_accuracy 0.38333333333333336
yhat counter: Counter({3: 570, 4: 473, 2: 393, 0: 365, 5: 285, 1: 248})
yhat counter: Counter({3: 81, 4: 56, 2: 50, 0: 42, 5: 41, 1: 30})
I 2, train_loss [[1.88829384]], train_accuracy 0.5497000856898029, dev_accuracy 0.43
yhat counter: Counter({2: 520, 3: 495, 4: 486, 5: 355, 1: 293, 0: 185})
yhat counter: Counter({2: 71, 3: 70, 4: 62, 5: 42, 1: 39, 0: 16})
I 3, train_loss [[1.58159645]], train_accuracy 0.5925449871465296, dev_accuracy 0.4533333333333333
yhat counter: Counter({1:

##### unigrams - linear classifier

In [182]:
importlib.reload(tl)
importlib.reload(config)
trained_ll_unigrams = tl.main(utils.text_to_unigrams)

problem dimensions are: (129, 6)
I 0, train_loss [[1.31432942e-09]], train_accuracy 0.6131105398457584, dev_accuracy 0.5433333333333333
I 1, train_loss [[11.04493302]], train_accuracy 0.34832904884318766, dev_accuracy 0.3433333333333333
I 2, train_loss [[62.19223377]], train_accuracy 0.572407883461868, dev_accuracy 0.52
I 3, train_loss [[8.12552919]], train_accuracy 0.7013710368466153, dev_accuracy 0.6033333333333334
I 4, train_loss [[27.68012363]], train_accuracy 0.7519280205655527, dev_accuracy 0.66
I 5, train_loss [[7.6716411e-14]], train_accuracy 0.7129391602399314, dev_accuracy 0.6166666666666667
early stopping criterion in iteration 6 - detriorating dev accuracy
top 7 scores for each language:
language: ['it'] bigrams: [('i', 4.51), ('o', 3.53), ('-', 2.59), ('è', 6.42), ('*', 3.29), ('ò', 2.89), ('ì', 3.22)]
language: ['nl'] bigrams: [('e', 1.94), ('k', 5.97), ('w', 3.17), ('j', 4.83), ('z', 3.18), ('x', 2.62), ('"', 1.99)]
language: ['en'] bigrams: [('t', 3.25), ('h', 3.56), ('

##### scoring on the dev set for mlp1

In [170]:
exec(open('train_mlp1.py').read())

problem dimensions are: (600, 150, 6)
yhat counter: Counter({3: 430, 0: 395, 2: 389, 1: 380, 5: 374, 4: 366})
yhat counter: Counter({3: 67, 1: 59, 5: 48, 2: 45, 4: 44, 0: 37})
I 0, train_loss [[3.97958122]], train_accuracy 0.86033, dev_accuracy 0.69667
yhat counter: Counter({5: 405, 3: 400, 0: 393, 2: 387, 1: 375, 4: 374})
yhat counter: Counter({3: 65, 1: 61, 2: 48, 5: 47, 0: 41, 4: 38})
I 1, train_loss [[0.82651095]], train_accuracy 0.94473, dev_accuracy 0.71000
yhat counter: Counter({3: 403, 2: 399, 4: 393, 5: 390, 1: 379, 0: 370})
yhat counter: Counter({3: 63, 1: 60, 2: 54, 5: 46, 4: 42, 0: 35})
I 2, train_loss [[0.24806087]], train_accuracy 0.98029, dev_accuracy 0.71667
yhat counter: Counter({2: 395, 0: 393, 5: 391, 4: 390, 1: 385, 3: 380})
yhat counter: Counter({1: 60, 3: 55, 2: 54, 5: 47, 4: 43, 0: 41})
I 3, train_loss [[0.07436868]], train_accuracy 0.99314, dev_accuracy 0.72333
yhat counter: Counter({2: 395, 5: 392, 4: 389, 3: 389, 0: 385, 1: 384})
yhat counter: Counter({1: 59, 

##### learn xor with mlp1

In [266]:
importlib.reload(tp1)
importlib.reload(mlp1)

<module 'mlp1' from 'C:\\Shahar\\BarIlan\\NLP-courses\\89687-DL\\Assignment1\\code\\mlp1.py'>

In [185]:
params = mlp1.create_classifier(2,2,2)
for i,p in enumerate(params):
    print("{}:\n{}".format(i,p))

0:
[[0. 0.]
 [0. 0.]]
1:
[[0. 0.]]
2:
[[0. 0.]
 [0. 0.]]
3:
[[0. 0.]]


In [257]:
xor_data = [(0,[0,0]),
        (1,[0,1]),
        (1,[1,0]),
        (0,[1,1])]

xor_data1 = [(np.array(b,np.double),a) for a, b in xor_data]
    
print(xor_data1)


[(array([0., 0.]), 0), (array([0., 1.]), 1), (array([1., 0.]), 1), (array([1., 1.]), 0)]


In [258]:
print(params)
for x,_ in xor_data1:
    print(x)
    print(mlp1.classifier_output(x,params))
    print(mlp1.predict(x, params))

[array([[ 1., -2.],
       [-2.,  1.]]), array([[0., 0.]]), array([[1., 0.],
       [0., 1.]]), array([[0., 0.]])]
[0. 0.]
[[0.5 0.5]]
0
[0. 1.]
[[0.15114846 0.84885154]]
1
[1. 0.]
[[0.84885154 0.15114846]]
0
[1. 1.]
[[0.5 0.5]]
0


In [294]:
# random initialization, 8 nodes in hidden layer - find a solution after 15 iterations
params = mlp1.create_classifier(2,8,2)
params= [tp1.randomize_array(p) for p in params]
tp1.train_classifier(xor_data1,xor_data1, 50, 0.03, params)

I 0, train_loss [[1.4963715]], train_accuracy 0.25, dev_accuracy 0.25
I 1, train_loss [[1.40295192]], train_accuracy 0.0, dev_accuracy 0.0
I 2, train_loss [[1.34500042]], train_accuracy 0.0, dev_accuracy 0.0
I 3, train_loss [[1.28547536]], train_accuracy 0.25, dev_accuracy 0.25
I 4, train_loss [[1.22405254]], train_accuracy 0.25, dev_accuracy 0.25
I 5, train_loss [[1.16917722]], train_accuracy 0.25, dev_accuracy 0.25
I 6, train_loss [[1.1126267]], train_accuracy 0.25, dev_accuracy 0.25
I 7, train_loss [[1.07140458]], train_accuracy 0.25, dev_accuracy 0.25
I 8, train_loss [[1.03259458]], train_accuracy 0.25, dev_accuracy 0.25
I 9, train_loss [[0.98999025]], train_accuracy 0.25, dev_accuracy 0.25
I 10, train_loss [[0.95372547]], train_accuracy 0.25, dev_accuracy 0.25
I 11, train_loss [[0.91575432]], train_accuracy 0.25, dev_accuracy 0.25
I 12, train_loss [[0.8849291]], train_accuracy 0.25, dev_accuracy 0.25
I 13, train_loss [[0.85413255]], train_accuracy 0.25, dev_accuracy 0.25
I 14, tra

[array([[ 0.11575217,  2.46127858,  0.98622363, -0.33974401, -0.37484117,
         -1.26843889,  1.16260803, -0.53241877],
        [ 0.02713331, -2.30037931,  0.45543964,  0.99312771, -0.38949908,
         -1.53179452, -0.88365079,  1.44681024]]),
 array([[-1.00542858, -1.06005401, -1.10225369,  1.52762519, -0.40965224,
          0.47889543,  0.58342752, -1.76313054]]),
 array([[-1.66627296,  0.36360198],
        [-1.36879416,  0.4332395 ],
        [ 0.48657708, -0.617737  ],
        [-0.82357282,  1.26372314],
        [-0.33317477,  0.12905255],
        [-0.54915025, -1.65997959],
        [ 1.66050276, -0.45921665],
        [ 0.44364825,  0.11431201]]),
 array([[-0.52134482, -0.12692229]])]

In [295]:
# with a 'good' initialization, finds a solution with hidden layer of 2
params = mlp1.create_classifier(2,2,2)
params[0] = np.array([[1, -2],[-2,1]],np.double)
params[2] = np.array([[1,0],[0,1]],np.double)
tp1.train_classifier(xor_data1,xor_data1, 50, 0.1, params)

I 0, train_loss [[0.91276037]], train_accuracy 0.75, dev_accuracy 0.75
I 1, train_loss [[0.8568009]], train_accuracy 0.75, dev_accuracy 0.75
I 2, train_loss [[0.81246094]], train_accuracy 0.75, dev_accuracy 0.75
I 3, train_loss [[0.77969098]], train_accuracy 0.75, dev_accuracy 0.75
I 4, train_loss [[0.75340166]], train_accuracy 0.75, dev_accuracy 0.75
I 5, train_loss [[0.73449051]], train_accuracy 0.75, dev_accuracy 0.75
I 6, train_loss [[0.71856006]], train_accuracy 0.75, dev_accuracy 0.75
I 7, train_loss [[0.70413183]], train_accuracy 0.75, dev_accuracy 0.75
I 8, train_loss [[0.69357204]], train_accuracy 0.75, dev_accuracy 0.75
I 9, train_loss [[0.68285643]], train_accuracy 0.75, dev_accuracy 0.75
I 10, train_loss [[0.67229184]], train_accuracy 0.75, dev_accuracy 0.75
I 11, train_loss [[0.66424958]], train_accuracy 0.75, dev_accuracy 0.75
I 12, train_loss [[0.65615703]], train_accuracy 0.5, dev_accuracy 0.5
I 13, train_loss [[0.64681685]], train_accuracy 0.5, dev_accuracy 0.5
I 14, t

[array([[ 1.6290629 , -2.30024073],
        [-2.16770801,  1.90669083]]),
 array([[-0.68511391, -0.92221966]]),
 array([[-0.57128102,  1.57128102],
        [-0.62629189,  1.62629189]]),
 array([[-0.82037082,  0.82037082]])]

In [280]:
# again random initialization, 8 nodes in hidden layer - this time took 28 iterations
params = mlp1.create_classifier(2,8,2)
params= [tp1.randomize_array(p) for p in params]
tp1.train_classifier(xor_data1,xor_data1, 50, 0.03, params)

I 0, train_loss [[1.47272509]], train_accuracy 0.75, dev_accuracy 0.75
I 1, train_loss [[1.36386236]], train_accuracy 0.75, dev_accuracy 0.75
I 2, train_loss [[1.27688689]], train_accuracy 0.75, dev_accuracy 0.75
I 3, train_loss [[1.2036548]], train_accuracy 0.75, dev_accuracy 0.75
I 4, train_loss [[1.13506959]], train_accuracy 0.75, dev_accuracy 0.75
I 5, train_loss [[1.06812893]], train_accuracy 0.75, dev_accuracy 0.75
I 6, train_loss [[1.0065561]], train_accuracy 0.75, dev_accuracy 0.75
I 7, train_loss [[0.9529166]], train_accuracy 0.75, dev_accuracy 0.75
I 8, train_loss [[0.89532149]], train_accuracy 0.75, dev_accuracy 0.75
I 9, train_loss [[0.85093343]], train_accuracy 0.75, dev_accuracy 0.75
I 10, train_loss [[0.80592049]], train_accuracy 0.75, dev_accuracy 0.75
I 11, train_loss [[0.76015241]], train_accuracy 0.75, dev_accuracy 0.75
I 12, train_loss [[0.72314418]], train_accuracy 0.75, dev_accuracy 0.75
I 13, train_loss [[0.68941323]], train_accuracy 0.75, dev_accuracy 0.75
I 14,

[array([[ 1.13807626, -1.49006735,  2.9052079 , -1.13293642, -1.52056728,
          2.15241804, -0.3411089 ,  0.25646264],
        [-1.88165898,  1.15483605,  1.24211427, -0.11865331,  1.71661387,
          1.59261188,  0.24743182,  0.50226388]]),
 array([[-0.06694138, -0.76238582,  1.50338027,  0.00940934, -2.5529656 ,
          0.13891737, -0.26571632,  0.2951348 ]]),
 array([[-0.62652053,  0.46964999],
        [-1.51713734,  0.35991392],
        [ 0.54134571, -0.06387941],
        [ 0.36611161,  0.35973603],
        [ 0.92964801,  1.03602574],
        [-0.55148122,  2.23605697],
        [-0.15633113, -0.37193097],
        [-0.93902404, -0.30274335]]),
 array([[1.45017026, 0.62842456]])]

In [281]:
# random initialization, 2 nodes in hidden layer - not there even after 500 iterations
params = mlp1.create_classifier(2,2,2)
params= [tp1.randomize_array(p) for p in params]
tp1.train_classifier(xor_data1,xor_data1, 500, 0.03, params)

I 0, train_loss [[1.38677239]], train_accuracy 0.5, dev_accuracy 0.5
I 1, train_loss [[1.32093041]], train_accuracy 0.5, dev_accuracy 0.5
I 2, train_loss [[1.25909662]], train_accuracy 0.5, dev_accuracy 0.5
I 3, train_loss [[1.20128375]], train_accuracy 0.5, dev_accuracy 0.5
I 4, train_loss [[1.14803849]], train_accuracy 0.5, dev_accuracy 0.5
I 5, train_loss [[1.09902633]], train_accuracy 0.5, dev_accuracy 0.5
I 6, train_loss [[1.05399705]], train_accuracy 0.5, dev_accuracy 0.5
I 7, train_loss [[1.01266492]], train_accuracy 0.5, dev_accuracy 0.5
I 8, train_loss [[0.97500586]], train_accuracy 0.5, dev_accuracy 0.5
I 9, train_loss [[0.94194114]], train_accuracy 0.5, dev_accuracy 0.5
I 10, train_loss [[0.91360522]], train_accuracy 0.5, dev_accuracy 0.5
I 11, train_loss [[0.88811166]], train_accuracy 0.5, dev_accuracy 0.5
I 12, train_loss [[0.86555997]], train_accuracy 0.5, dev_accuracy 0.5
I 13, train_loss [[0.84665364]], train_accuracy 0.5, dev_accuracy 0.5
I 14, train_loss [[0.82971828]

I 128, train_loss [[0.59631464]], train_accuracy 0.5, dev_accuracy 0.5
I 129, train_loss [[0.59485942]], train_accuracy 0.5, dev_accuracy 0.5
I 130, train_loss [[0.59348131]], train_accuracy 0.5, dev_accuracy 0.5
I 131, train_loss [[0.59191293]], train_accuracy 0.5, dev_accuracy 0.5
I 132, train_loss [[0.59049645]], train_accuracy 0.5, dev_accuracy 0.5
I 133, train_loss [[0.58908173]], train_accuracy 0.5, dev_accuracy 0.5
I 134, train_loss [[0.5876745]], train_accuracy 0.5, dev_accuracy 0.5
I 135, train_loss [[0.58628011]], train_accuracy 0.5, dev_accuracy 0.5
I 136, train_loss [[0.58444128]], train_accuracy 0.5, dev_accuracy 0.5
I 137, train_loss [[0.58320634]], train_accuracy 0.5, dev_accuracy 0.5
I 138, train_loss [[0.58210297]], train_accuracy 0.5, dev_accuracy 0.5
I 139, train_loss [[0.58041211]], train_accuracy 0.5, dev_accuracy 0.5
I 140, train_loss [[0.5791504]], train_accuracy 0.5, dev_accuracy 0.5
I 141, train_loss [[0.57801464]], train_accuracy 0.5, dev_accuracy 0.5
I 142, t

I 260, train_loss [[0.45896412]], train_accuracy 0.5, dev_accuracy 0.5
I 261, train_loss [[0.45845391]], train_accuracy 0.5, dev_accuracy 0.5
I 262, train_loss [[0.45788825]], train_accuracy 0.5, dev_accuracy 0.5
I 263, train_loss [[0.45729144]], train_accuracy 0.5, dev_accuracy 0.5
I 264, train_loss [[0.45672438]], train_accuracy 0.5, dev_accuracy 0.5
I 265, train_loss [[0.45613806]], train_accuracy 0.5, dev_accuracy 0.5
I 266, train_loss [[0.4555411]], train_accuracy 0.5, dev_accuracy 0.5
I 267, train_loss [[0.45496394]], train_accuracy 0.5, dev_accuracy 0.5
I 268, train_loss [[0.4544068]], train_accuracy 0.5, dev_accuracy 0.5
I 269, train_loss [[0.45378505]], train_accuracy 0.5, dev_accuracy 0.5
I 270, train_loss [[0.45321355]], train_accuracy 0.5, dev_accuracy 0.5
I 271, train_loss [[0.45272494]], train_accuracy 0.5, dev_accuracy 0.5
I 272, train_loss [[0.45219654]], train_accuracy 0.5, dev_accuracy 0.5
I 273, train_loss [[0.45165073]], train_accuracy 0.5, dev_accuracy 0.5
I 274, t

I 394, train_loss [[0.41059111]], train_accuracy 0.5, dev_accuracy 0.5
I 395, train_loss [[0.41034895]], train_accuracy 0.5, dev_accuracy 0.5
I 396, train_loss [[0.41011175]], train_accuracy 0.5, dev_accuracy 0.5
I 397, train_loss [[0.40995169]], train_accuracy 0.5, dev_accuracy 0.5
I 398, train_loss [[0.40974688]], train_accuracy 0.5, dev_accuracy 0.5
I 399, train_loss [[0.40951564]], train_accuracy 0.5, dev_accuracy 0.5
I 400, train_loss [[0.40931853]], train_accuracy 0.5, dev_accuracy 0.5
I 401, train_loss [[0.40912672]], train_accuracy 0.5, dev_accuracy 0.5
I 402, train_loss [[0.40896361]], train_accuracy 0.5, dev_accuracy 0.5
I 403, train_loss [[0.40875472]], train_accuracy 0.5, dev_accuracy 0.5
I 404, train_loss [[0.40859083]], train_accuracy 0.5, dev_accuracy 0.5
I 405, train_loss [[0.4083963]], train_accuracy 0.5, dev_accuracy 0.5
I 406, train_loss [[0.40817295]], train_accuracy 0.5, dev_accuracy 0.5
I 407, train_loss [[0.40802067]], train_accuracy 0.5, dev_accuracy 0.5
I 408, 

[array([[-2.6575517 ,  2.4032252 ],
        [-1.79421065, -1.19616546]]),
 array([[0.39583318, 0.96122829]]),
 array([[ 2.0974537 , -0.78567593],
        [ 0.44178191, -2.44642556]]),
 array([[0.53592355, 0.54559255]])]

In [289]:
# with the right initialization, find a solution with 2 nodes in hidden layer 
params = mlp1.create_classifier(2,2,2)
params[0] = np.array([[-2, 0],[8,-2]],np.double)
params[2] = np.array([[1, 0],[0,1]],np.double)

params= [tp1.randomize_array(p) for p in params]
tp1.train_classifier(xor_data1,xor_data1, 60, 0.08, params)

I 0, train_loss [[0.83059606]], train_accuracy 0.5, dev_accuracy 0.5
I 1, train_loss [[0.78464472]], train_accuracy 0.5, dev_accuracy 0.5
I 2, train_loss [[0.75799416]], train_accuracy 0.5, dev_accuracy 0.5
I 3, train_loss [[0.74336083]], train_accuracy 0.5, dev_accuracy 0.5
I 4, train_loss [[0.73043821]], train_accuracy 0.5, dev_accuracy 0.5
I 5, train_loss [[0.72221679]], train_accuracy 0.75, dev_accuracy 0.75
I 6, train_loss [[0.71767411]], train_accuracy 0.75, dev_accuracy 0.75
I 7, train_loss [[0.71278409]], train_accuracy 0.75, dev_accuracy 0.75
I 8, train_loss [[0.71140494]], train_accuracy 0.75, dev_accuracy 0.75
I 9, train_loss [[0.70988464]], train_accuracy 0.75, dev_accuracy 0.75
I 10, train_loss [[0.7085625]], train_accuracy 0.75, dev_accuracy 0.75
I 11, train_loss [[0.70806615]], train_accuracy 0.75, dev_accuracy 0.75
I 12, train_loss [[0.70695922]], train_accuracy 0.75, dev_accuracy 0.75
I 13, train_loss [[0.706111]], train_accuracy 0.75, dev_accuracy 0.75
I 14, train_los

[array([[ 0.63715567, -1.18961662],
        [-0.54689541,  1.53239254]]),
 array([[0.32293775, 0.76573247]]),
 array([[ 0.58183756, -0.12011371],
        [ 1.22618957, -0.05978381]]),
 array([[0.47750499, 1.23095538]])]

In [236]:
classifier_output()

[array([[ 1., -2.],
        [-2.,  1.]]), array([[0., 0.]]), array([[1., 0.],
        [0., 1.]]), array([[0., 0.]])]

In [310]:
import mlpn
importlib.reload(mlpn)
import testing
importlib.reload(testing)
import grad_check
importlib.reload(grad_check)
importlib.reload(config)
testing.mlpn_grad_sanity()

b_tag
Gradient check passed!
U:
Gradient check passed!
b:
Gradient check passed!
W:
Gradient check passed!


In [311]:
exec(open('train_mlpn.py').read())

I 0, train_loss [[2.11002989]], train_accuracy 0.55356, dev_accuracy 0.48333
I 1, train_loss [[1.13759603]], train_accuracy 0.67138, dev_accuracy 0.51333
I 2, train_loss [[0.90771125]], train_accuracy 0.74679, dev_accuracy 0.57000
I 3, train_loss [[0.74984542]], train_accuracy 0.79434, dev_accuracy 0.58667
I 4, train_loss [[0.6340787]], train_accuracy 0.81577, dev_accuracy 0.61000
I 5, train_loss [[0.5430263]], train_accuracy 0.85733, dev_accuracy 0.63000
I 6, train_loss [[0.4557463]], train_accuracy 0.88432, dev_accuracy 0.65667
I 7, train_loss [[0.38172133]], train_accuracy 0.89760, dev_accuracy 0.63667
early stopping criterion in iteration 7 - detriorating dev accuracy
