In [1]:
import pickle
import numpy as np

In [2]:
with open('ex1_embed_mat50.pickle','rb') as a:
    E = pickle.load(a)

In [3]:
type(E)

numpy.ndarray

In [4]:
E.shape

(50L, 43129L)

In [5]:
E.sum()

11.598446355544638

In [7]:
sum(np.sum(E,axis=0)==0)

0

In [8]:
from scipy.spatial.distance import cosine

In [13]:
from collections import Counter, OrderedDict
def scan_train_for_vocab(train_data):
    words = Counter()
    tags = Counter()
    for line in train_data:
        if len(line) > 1:
            word, tag = line.split()
            words[word] += 1
            tags[tag] += 1
        
    word_list = [a for a, _ in words.most_common()]
    tag_list = [a for a, _ in tags.most_common()]
    word_dict = OrderedDict((a,i) for i, a in enumerate(word_list))
    tag_dict = OrderedDict((a,i) for i, a in enumerate(tag_list))
    return word_dict, tag_dict


In [14]:

with open('../pos/train','rt') as a:
    word_dict,tag_dict = scan_train_for_vocab(a)

In [58]:
for i in range(200,300,10):
    print(i,word_dict.keys()[i:i+10])

(200, ['own', 'bank', 'profit', 'big', 'recent', 'products', 'being', 'should', 'analysts', 'these'])
(210, ['debt', 'part', 'securities', 'including', 'higher', '15', 'offer', 'well', 'work', 'tax'])
(220, ['8', 'past', 'reported', 'operations', 'take', 'her', 'sale', 'This', 'Japan', 'funds'])
(230, ['?', 'If', 'lower', 'House', 'way', '1988', 'end', 'plans', 'she', 'increase'])
(240, ['closed', 'both', 'sold', 'yield', 'Friday', 'during', 'very', 'less', 'loss', 'Bank'])
(250, ['markets', 'vice', 'growth', 'bid', 'each', 'where', 'another', 'costs', 'issues', 'how'])
(260, ['pay', 'our', 'used', 'Bush', 'five', 'As', 'economic', 'due', 'National', 'few'])
(270, ["'re", 'high', 'average', 'common', '20', 'several', 'him', 'good', 'use', 'current'])
(280, ['banks', 'British', 'yen', 'cash', 'At', 'day', 'third', 'then', 'least', 'San'])
(290, ['revenue', '50', '2', 'Stock', 'California', 'report', 'foreign', 'might', '1989', 'assets'])


In [20]:
word_dict.keys()[62]

'share'

In [22]:
v = E[:,62]

In [23]:
dist = [cosine(E[:,i],v) for i in xrange(43129)]

In [24]:
len(dist)

43129

In [25]:
distnp = np.array(dist)

In [26]:
np.histogram(distnp)

(array([    2,   115,   609,  2229, 11124, 18476,  8391,  1556,   552,
           75], dtype=int64),
 array([0.        , 0.18548872, 0.37097744, 0.55646616, 0.74195488,
        0.9274436 , 1.11293232, 1.29842104, 1.48390976, 1.66939848,
        1.8548872 ]))

In [42]:
np.nonzero(distnp<0.22)

(array([  62,   88,  134,  269,  565, 1215], dtype=int64),)

In [39]:
word_dict.keys()[176]

'still'

In [43]:
[word_dict.keys()[i] for i in [  62,   88,  134,  269,  565, 1215]]

['share', 'because', 'so', 'few', 'July', 'minimum']

In [46]:
word_dict.keys()[39]

'year'

In [54]:
v = E[:,62]
dist_year = np.array([cosine(E[:,i],v) for i in xrange(43129)])
[word_dict.keys()[i] for i in np.nonzero(dist_year< sorted(dist_year)[10])[0].tolist()]

['share',
 'because',
 'so',
 'still',
 'few',
 'July',
 'key',
 'minimum',
 'ease',
 '45-year-old']

In [55]:
v = E[:,39]
dist_year = np.array([cosine(E[:,i],v) for i in xrange(43129)])
[word_dict.keys()[i] for i in np.nonzero(dist_year< sorted(dist_year)[10])[0].tolist()]

['year',
 'Last',
 'arrested',
 'Congressional',
 'canning',
 '10.43',
 'Evaluating',
 '32-nation',
 'Honors',
 '390-million']

In [56]:
v = E[:,94]
dist_year = np.array([cosine(E[:,i],v) for i in xrange(43129)])
[word_dict.keys()[i] for i in np.nonzero(dist_year< sorted(dist_year)[10])[0].tolist()]

['%',
 'be',
 'only',
 'can',
 'technique',
 'managements',
 'pillowcases',
 '60-inch',
 'plugged',
 '120,000-employee']

In [57]:
v = E[:,63]
dist_year = np.array([cosine(E[:,i],v) for i in xrange(43129)])
[word_dict.keys()[i] for i in np.nonzero(dist_year< sorted(dist_year)[10])[0].tolist()]

['also',
 'Japan',
 'network',
 'contributed',
 'Hewlett-Packard',
 'Virginia',
 'Pa.',
 'Commonwealth',
 '6,400',
 'high-minded']

In [59]:
v = E[:,293]
dist_year = np.array([cosine(E[:,i],v) for i in xrange(43129)])
[word_dict.keys()[i] for i in np.nonzero(dist_year< sorted(dist_year)[10])[0].tolist()]

['Stock',
 'late',
 'number',
 'Like',
 'Besides',
 'middlemen',
 'successors',
 'non-Communist',
 '4.35',
 'dynasty']