In [1]:
import pickle
import numpy as np

In [2]:
with open('ex1_embed_mat50.pickle','rb') as a:
    E = pickle.load(a)

In [3]:
type(E)

numpy.ndarray

In [4]:
E.shape

(50L, 43129L)

In [5]:
E.sum()

11.598446355544638

In [7]:
sum(np.sum(E,axis=0)==0)

0

In [8]:
from scipy.spatial.distance import cosine

In [13]:
from collections import Counter, OrderedDict
def scan_train_for_vocab(train_data):
    words = Counter()
    tags = Counter()
    for line in train_data:
        if len(line) > 1:
            word, tag = line.split()
            words[word] += 1
            tags[tag] += 1
        
    word_list = [a for a, _ in words.most_common()]
    tag_list = [a for a, _ in tags.most_common()]
    word_dict = OrderedDict((a,i) for i, a in enumerate(word_list))
    tag_dict = OrderedDict((a,i) for i, a in enumerate(tag_list))
    return word_dict, tag_dict


In [14]:

with open('../pos/train','rt') as a:
    word_dict,tag_dict = scan_train_for_vocab(a)

In [58]:
for i in range(200,300,10):
    print(i,word_dict.keys()[i:i+10])

(200, ['own', 'bank', 'profit', 'big', 'recent', 'products', 'being', 'should', 'analysts', 'these'])
(210, ['debt', 'part', 'securities', 'including', 'higher', '15', 'offer', 'well', 'work', 'tax'])
(220, ['8', 'past', 'reported', 'operations', 'take', 'her', 'sale', 'This', 'Japan', 'funds'])
(230, ['?', 'If', 'lower', 'House', 'way', '1988', 'end', 'plans', 'she', 'increase'])
(240, ['closed', 'both', 'sold', 'yield', 'Friday', 'during', 'very', 'less', 'loss', 'Bank'])
(250, ['markets', 'vice', 'growth', 'bid', 'each', 'where', 'another', 'costs', 'issues', 'how'])
(260, ['pay', 'our', 'used', 'Bush', 'five', 'As', 'economic', 'due', 'National', 'few'])
(270, ["'re", 'high', 'average', 'common', '20', 'several', 'him', 'good', 'use', 'current'])
(280, ['banks', 'British', 'yen', 'cash', 'At', 'day', 'third', 'then', 'least', 'San'])
(290, ['revenue', '50', '2', 'Stock', 'California', 'report', 'foreign', 'might', '1989', 'assets'])


In [20]:
word_dict.keys()[62]

'share'

In [22]:
v = E[:,62]

In [23]:
dist = [cosine(E[:,i],v) for i in xrange(43129)]

In [24]:
len(dist)

43129

In [25]:
distnp = np.array(dist)

In [26]:
np.histogram(distnp)

(array([    2,   115,   609,  2229, 11124, 18476,  8391,  1556,   552,
           75], dtype=int64),
 array([0.        , 0.18548872, 0.37097744, 0.55646616, 0.74195488,
        0.9274436 , 1.11293232, 1.29842104, 1.48390976, 1.66939848,
        1.8548872 ]))

In [42]:
np.nonzero(distnp<0.22)

(array([  62,   88,  134,  269,  565, 1215], dtype=int64),)

In [39]:
word_dict.keys()[176]

'still'

In [43]:
[word_dict.keys()[i] for i in [  62,   88,  134,  269,  565, 1215]]

['share', 'because', 'so', 'few', 'July', 'minimum']

In [46]:
word_dict.keys()[39]

'year'

In [95]:
E.shape

(100232L, 50L)

In [96]:
sim = np.dot(E,E[4,:])

In [106]:
np.sqrt(np.diag(E[:10,:].dot(E[:10,:].T)))


array([2.75764334, 4.64814072, 3.97642237, 5.24285991, 4.17649652,
       4.21715167, 4.94851393, 4.46602819, 5.59767374, 5.43658436])

In [110]:
nn=np.sum(E[:10,:]**2,axis=1)**(1./2)
print nn

[2.75764334 4.64814072 3.97642237 5.24285991 4.17649652 4.21715167
 4.94851393 4.46602819 5.59767374 5.43658436]


In [115]:
E[[2,4,5],:]

array([[-0.408797, -0.109333, -0.099279, -0.857098, -0.150319, -0.456398,
        -0.781524, -0.059621,  0.302548,  0.202162, -0.319892, -0.502241,
        -0.014925,  0.020889,  1.506245,  0.24753 ,  0.385598, -0.170776,
         0.32596 ,  0.267304,  0.157673,  0.12554 , -0.971452, -0.485595,
         0.487857,  0.284369, -0.062811, -1.334082,  0.744133,  0.572701,
         1.009871, -0.457229,  0.938059,  0.654805, -0.430244, -0.697683,
        -0.220146,  0.346002, -0.388637, -0.149513,  0.011248,  0.818728,
         0.042615, -0.594237, -0.646138,  0.568898,  0.700328,  0.290316,
         0.293722,  0.828779],
       [-0.811262, -1.017245,  0.31168 , -0.437684,  0.338728,  1.034527,
        -0.415528, -0.646984, -0.121626,  0.589435, -0.977225,  0.099942,
        -1.296171,  0.022671,  0.946574,  0.204963,  0.297055, -0.394868,
         0.028115, -0.021189, -0.448692,  0.421286,  0.156809, -0.332004,
         0.177866,  0.074233,  0.299713,  0.148349,  1.104055, -0.17272 ,
       

In [118]:
np.argsort(np.array([[6,5,9,8,1],[4,7,9,0,2]]),axis=0)

array([[1, 0, 0, 1, 0],
       [0, 1, 1, 0, 1]], dtype=int64)

In [120]:
list(np.arange(5))

[0, 1, 2, 3, 4]

In [108]:
normalized_E10 = E[:10,:]/nn[:,np.newaxis]

In [121]:
cosine(np.array([1.,1.]),np.array([-1.,-1.]))

2.0

In [109]:
np.sum(normalized_E10**2,axis=-1)**(1./2)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [54]:
v = E[:,62]
dist_year = np.array([cosine(E[:,i],v) for i in xrange(43129)])
[word_dict.keys()[i] for i in np.nonzero(dist_year< sorted(dist_year)[10])[0].tolist()]

['share',
 'because',
 'so',
 'still',
 'few',
 'July',
 'key',
 'minimum',
 'ease',
 '45-year-old']

In [55]:
v = E[:,39]
dist_year = np.array([cosine(E[:,i],v) for i in xrange(43129)])
[word_dict.keys()[i] for i in np.nonzero(dist_year< sorted(dist_year)[10])[0].tolist()]

['year',
 'Last',
 'arrested',
 'Congressional',
 'canning',
 '10.43',
 'Evaluating',
 '32-nation',
 'Honors',
 '390-million']

In [56]:
v = E[:,94]
dist_year = np.array([cosine(E[:,i],v) for i in xrange(43129)])
[word_dict.keys()[i] for i in np.nonzero(dist_year< sorted(dist_year)[10])[0].tolist()]

['%',
 'be',
 'only',
 'can',
 'technique',
 'managements',
 'pillowcases',
 '60-inch',
 'plugged',
 '120,000-employee']

In [57]:
v = E[:,63]
dist_year = np.array([cosine(E[:,i],v) for i in xrange(43129)])
[word_dict.keys()[i] for i in np.nonzero(dist_year< sorted(dist_year)[10])[0].tolist()]

['also',
 'Japan',
 'network',
 'contributed',
 'Hewlett-Packard',
 'Virginia',
 'Pa.',
 'Commonwealth',
 '6,400',
 'high-minded']

In [59]:
v = E[:,293]
dist_year = np.array([cosine(E[:,i],v) for i in xrange(43129)])
[word_dict.keys()[i] for i in np.nonzero(dist_year< sorted(dist_year)[10])[0].tolist()]

['Stock',
 'late',
 'number',
 'Like',
 'Besides',
 'middlemen',
 'successors',
 'non-Communist',
 '4.35',
 'dynasty']

In [71]:
E = np.fromfile('../wordVectors.txt', sep=' ')

In [76]:
E = E.reshape(E.shape[0]/50,50)
E.shape

(100232L, 50L)

In [77]:
E[0,:]

array([ 0.172414, -0.091063,  0.255125, -0.837163,  0.434872, -0.499848,
       -0.042904, -0.059642, -0.635087, -0.458795, -0.105671,  0.506513,
       -0.105105, -0.405678,  0.493365,  0.408807,  0.401635, -0.817805,
        0.62634 ,  0.580636, -0.246996, -0.008515, -0.67114 ,  0.301865,
       -0.439651,  0.247694, -0.291402,  0.873009,  0.216212,  0.145576,
       -0.211101, -0.35236 ,  0.227651, -0.118416,  0.371816,  0.261296,
        0.017548,  0.596692, -0.485722, -0.36953 , -0.048807,  0.01796 ,
       -0.040483,  0.111193,  0.398039,  0.162765,  0.408946,  0.005343,
       -0.107523, -0.079821])

In [91]:
def cosine_dist(x,y):
    return np.dot(x,y)/np.sqrt((np.dot(x,x)*np.dot(y,y)))

In [92]:
print(1 - cosine_dist(E[0,:],E[1,:]))
print(cosine(E[0,:],E[1,:]))

0.881723248107092
0.8817232481070921


In [94]:
print(np.dot(E[0,:],E[0,:]))

7.604596768618


In [83]:
nu = lambda word: len(set(word) - set('-+,.0123456789')) ==0


In [86]:
nu('1,456.24w')

False

In [82]:
set('1456') - set('-+,.0123456789')

set()

In [88]:
'my-god'.rsplit('-',1)[0]

'my'