In [6]:

from importlib import reload
import numpy as np
from collections import Counter

### Testing the processing of the input
from the text file to countrs

In [59]:
import training
reload(training)

<module 'training' from 'C:\\Shahar\\BarIlan\\NLP-courses\\89680-NLP\\assignment1\\code\\training.py'>

In [60]:
train_data = training.read_input('..\\data\\ass1-tagger-train')

string length: 8237657 words:950028 


In [35]:
train_data.pos_counter1

array([[16252, 35541,  1307, ...,     0,     7,     0],
       [11424,  2232, 15763, ...,     2,     2,     1],
       [ 5344,  3889, 34528, ...,     0,     3,     0],
       ...,
       [    2,     7,     0, ...,     3,     0,     0],
       [    4,     2,     3, ...,     0,     0,     0],
       [    0,     0,     0, ...,     0,     0,     0]])

In [12]:
train_data.pos_counter1[0,0]


16252

In [15]:
with open('..\\data\\ass1-tagger-train','rt',encoding='utf8') as a:
        file_as_string = a.read()

    # single counters
word_pos_pairs = [w.rsplit("/",1) for w in file_as_string.split()] #rsplit("/",1): split on the first slash from the right
   

In [20]:
c = 0
prev = False
for p in word_pos_pairs:
    if p[1]=='NNP':
        if prev:
            c +=1
    if p[1]=='NN':
        prev=True
    else:
        prev=False
print(c)

1307


In [16]:
train_data.pos_items

{'NN': 0,
 'IN': 1,
 'NNP': 2,
 'DT': 3,
 'JJ': 4,
 'NNS': 5,
 ',': 6,
 '.': 7,
 'CD': 8,
 'RB': 9,
 'VBD': 10,
 'VB': 11,
 'CC': 12,
 'VBZ': 13,
 'VBN': 14,
 'PRP': 15,
 'VBG': 16,
 'TO': 17,
 'VBP': 18,
 'MD': 19,
 'POS': 20,
 'PRP$': 21,
 '$': 22,
 '``': 23,
 "''": 24,
 ':': 25,
 'WDT': 26,
 'JJR': 27,
 'NNPS': 28,
 'RP': 29,
 'WP': 30,
 'WRB': 31,
 'JJS': 32,
 'RBR': 33,
 ')': 34,
 '(': 35,
 'EX': 36,
 'RBS': 37,
 'PDT': 38,
 'FW': 39,
 'WP$': 40,
 '#': 41,
 'UH': 42,
 'SYM': 43,
 'LS': 44}

In [44]:
train_data.pos_counter2.most_common(10)

[(('IN', 'DT', 'NN'), 15800),
 (('DT', 'JJ', 'NN'), 12188),
 (('DT', 'NN', 'IN'), 11674),
 (('NN', 'IN', 'DT'), 11498),
 (('NNP', 'NNP', 'NNP'), 9212),
 (('IN', 'DT', 'JJ'), 8086),
 (('JJ', 'NN', 'IN'), 7652),
 (('NNP', 'NNP', ','), 6971),
 (('IN', 'NNP', 'NNP'), 6242),
 (('NN', 'IN', 'NNP'), 6046)]

In [47]:
c = 0
prev = ['start']*3
for p in word_pos_pairs:
    prev.append(p[1])
    prev = prev[1:]
    if all([x==y for x,y in zip(prev, ['NNP','NNP',','])]):
            c +=1
print(c)

6971


In [61]:
a=iter(train_data.word_counts.items())
print(next(a))
print(next(a))
print(next(a))
print(next(a))
print(next(a))


(',', array([    0,     0,     0,     0,     0,     0, 48723,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0]))
('the', array([    1,     0,     5, 41098,     2,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           1,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0]))
('.', array([    0,     0,     0,     0,     0,     0,     0, 39020,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,    

In [64]:
print(next(a))
print(next(a))
print(next(a))
print(next(a))

('for', array([   0, 7971,    0,    0,    0,    0,    0,    0,    0,    1,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    4,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0]))
('$', array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       7184,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0]))
('``', array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0, 6967,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0]))
('is', array([   0,    0,    0,    0,    0,    2,    0,   

### testing getQ

In [77]:
import training
import config
reload(training)
reload(config)

<module 'config' from 'C:\\Shahar\\BarIlan\\NLP-courses\\89680-NLP\\assignment1\\code\\config.py'>

In [78]:
training.getQ(('NNP', 'NNP', 'IN'),train_data)

count_abc: 1880	 count_ab: 34528
count_bc: 3889	count_b:91466
count_c:107862	numwods:950028
ret:0.06031972574374116


array([0.05444856, 0.04251853, 0.1135356 ])

In [79]:
np.array([0.05444856, 0.04251853, 0.1135356 ]).dot(np.array([3,2,1]))/(6)

0.06031972333333333

In [85]:
v = np.outer(np.random.rand(3),np.random.rand(3))
v

array([[0.488167  , 0.72041033, 0.69743804],
       [0.40514067, 0.59788459, 0.57881937],
       [0.03069406, 0.04529662, 0.04385221]])

In [92]:
e=np.min(v,axis=0)
print(e.T)
print(np.tile(e,(5,1)))

[0.03069406 0.04529662 0.04385221]
[[0.03069406 0.04529662 0.04385221]
 [0.03069406 0.04529662 0.04385221]
 [0.03069406 0.04529662 0.04385221]
 [0.03069406 0.04529662 0.04385221]
 [0.03069406 0.04529662 0.04385221]]
