In [1]:

from importlib import reload
import numpy as np
from collections import Counter

### Testing the processing of the input
from the text file to countrs

In [2]:
import training
reload(training)

<module 'training' from 'C:\\Shahar\\BarIlan\\NLP-courses\\89680-NLP\\assignment1\\code\\training.py'>

In [3]:
train_data = training.read_input('..\\data\\ass1-tagger-train')

In [4]:
train_data.pos_counter1

array([[16241, 35537,  1296, ...,     0,     4,     0],
       [11422,  2228, 15759, ...,     2,     2,     1],
       [ 5335,  3882, 34465, ...,     0,     1,     0],
       ...,
       [    2,     7,     0, ...,     3,     0,     0],
       [    3,     2,     2, ...,     0,     0,     0],
       [    0,     0,     0, ...,     0,     0,     0]])

In [7]:
train_data.pos_counter1.shape

(47, 47)

In [8]:
np.sum(train_data.pos_counter1, axis=0)

array([132935, 107862,  91466,  81832,  61217,  59856,  48727,      0,
        39832,  39478,  36568,  30970,  29889,  26438,  23959,  21672,
        20024,  17436,  14846,  13049,  12491,   9803,   8701,   8407,
         7372,   7092,   6919,   4772,   4294,   3238,   2673,   2662,
         2363,   2143,   1947,   1768,   1376,   1366,    863,    451,
          368,    234,    168,    142,     97,     58,     36])

In [10]:
np.sum(train_data.pos_counter1, axis=1)

array([132869, 107830,  91342,  81825,  61213,  59797,  48721,  39832,
        39832,   2765,  36545,  30956,  29886,  26434,  23959,  21671,
        20020,  17436,  14846,  13049,  12490,   9803,   8701,   8407,
         7372,   7076,   4640,   4473,   4294,   3237,   2652,   2661,
         2363,   2143,   1947,   1768,   1227,   1366,    863,    451,
          368,    234,    168,    142,     97,     53,     36])

In [9]:
train_data.pos_items

OrderedDict([('NN', 0),
             ('IN', 1),
             ('NNP', 2),
             ('DT', 3),
             ('JJ', 4),
             ('NNS', 5),
             (',', 6),
             ('*', 7),
             ('**', 8),
             ('.', 9),
             ('CD', 10),
             ('RB', 11),
             ('VBD', 12),
             ('VB', 13),
             ('CC', 14),
             ('VBZ', 15),
             ('VBN', 16),
             ('PRP', 17),
             ('VBG', 18),
             ('TO', 19),
             ('VBP', 20),
             ('MD', 21),
             ('POS', 22),
             ('PRP$', 23),
             ('$', 24),
             ('``', 25),
             ("''", 26),
             (':', 27),
             ('WDT', 28),
             ('JJR', 29),
             ('NNPS', 30),
             ('RP', 31),
             ('WP', 32),
             ('WRB', 33),
             ('JJS', 34),
             ('RBR', 35),
             (')', 36),
             ('(', 37),
             ('EX', 38),
             ('RBS', 39)

In [12]:
train_data.pos_counter1[0,0]


16252

In [15]:
with open('..\\data\\ass1-tagger-train','rt',encoding='utf8') as a:
        file_as_string = a.read()

    # single counters
word_pos_pairs = [w.rsplit("/",1) for w in file_as_string.split()] #rsplit("/",1): split on the first slash from the right
   

In [20]:
c = 0
prev = False
for p in word_pos_pairs:
    if p[1]=='NNP':
        if prev:
            c +=1
    if p[1]=='NN':
        prev=True
    else:
        prev=False
print(c)

1307


In [16]:
train_data.pos_items

{'NN': 0,
 'IN': 1,
 'NNP': 2,
 'DT': 3,
 'JJ': 4,
 'NNS': 5,
 ',': 6,
 '.': 7,
 'CD': 8,
 'RB': 9,
 'VBD': 10,
 'VB': 11,
 'CC': 12,
 'VBZ': 13,
 'VBN': 14,
 'PRP': 15,
 'VBG': 16,
 'TO': 17,
 'VBP': 18,
 'MD': 19,
 'POS': 20,
 'PRP$': 21,
 '$': 22,
 '``': 23,
 "''": 24,
 ':': 25,
 'WDT': 26,
 'JJR': 27,
 'NNPS': 28,
 'RP': 29,
 'WP': 30,
 'WRB': 31,
 'JJS': 32,
 'RBR': 33,
 ')': 34,
 '(': 35,
 'EX': 36,
 'RBS': 37,
 'PDT': 38,
 'FW': 39,
 'WP$': 40,
 '#': 41,
 'UH': 42,
 'SYM': 43,
 'LS': 44}

In [44]:
train_data.pos_counter2.most_common(10)

[(('IN', 'DT', 'NN'), 15800),
 (('DT', 'JJ', 'NN'), 12188),
 (('DT', 'NN', 'IN'), 11674),
 (('NN', 'IN', 'DT'), 11498),
 (('NNP', 'NNP', 'NNP'), 9212),
 (('IN', 'DT', 'JJ'), 8086),
 (('JJ', 'NN', 'IN'), 7652),
 (('NNP', 'NNP', ','), 6971),
 (('IN', 'NNP', 'NNP'), 6242),
 (('NN', 'IN', 'NNP'), 6046)]

In [5]:
train_data.pos_counter2.most_common(10)

[(('IN', 'DT', 'NN'), 15796),
 (('DT', 'JJ', 'NN'), 12188),
 (('DT', 'NN', 'IN'), 11674),
 (('NN', 'IN', 'DT'), 11495),
 (('NNP', 'NNP', 'NNP'), 9129),
 (('*', '**', 'DT'), 8645),
 (('IN', 'DT', 'JJ'), 8084),
 (('*', '**', 'NNP'), 8036),
 (('JJ', 'NN', 'IN'), 7652),
 (('NNP', 'NNP', ','), 6961)]

In [47]:
c = 0
prev = ['start']*3
for p in word_pos_pairs:
    prev.append(p[1])
    prev = prev[1:]
    if all([x==y for x,y in zip(prev, ['NNP','NNP',','])]):
            c +=1
print(c)

6971


In [6]:
a=iter(train_data.word_counts.items())
print(next(a))
print(next(a))
print(next(a))
print(next(a))
print(next(a))


('', array([    0,     0,     0,     0,     0,     0,     0, 39832, 39832,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0]))
('In', array([   0, 1735,    3,    0,    0,    0,    0,    0,    0,    0,    0,
          1,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    1,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0]))
('an', array([   0,    0,    0, 3142,    0,    0,    1,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    

In [64]:
print(next(a))
print(next(a))
print(next(a))
print(next(a))

('for', array([   0, 7971,    0,    0,    0,    0,    0,    0,    0,    1,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    4,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0]))
('$', array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       7184,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0]))
('``', array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0, 6967,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0]))
('is', array([   0,    0,    0,    0,    0,    2,    0,   

### testing getQ

In [106]:
import training
import config
reload(training)
reload(config)

<module 'config' from 'C:\\Shahar\\BarIlan\\NLP-courses\\89680-NLP\\assignment1\\code\\config.py'>

In [107]:
training.getQ(('NNP', 'NNP', 'IN'),train_data)

count_abc: 1880	 count_ab: 34528
count_bc: 3889	count_b:91466
count_c:107862	numwods:950028
ret:0.06031972574374116


0.06031972574374116

In [95]:
np.array([0.05444856, 0.04251853, 0.1135356 ]).dot(np.array([3,2,1]))/(6)

0.06031972333333333

In [85]:
v = np.outer(np.random.rand(3),np.random.rand(3))
v

array([[0.488167  , 0.72041033, 0.69743804],
       [0.40514067, 0.59788459, 0.57881937],
       [0.03069406, 0.04529662, 0.04385221]])

In [96]:
training.getLogQ(('NNP', 'NNP', 'IN'),train_data)

count_abc: 1880	 count_ab: 34528
count_bc: 3889	count_b:91466
count_c:107862	numwods:950028
ret:0.06031972574374116


2.808096101981414

In [97]:
np.log(0.06031972574374116)

-2.808096101981414

In [108]:
training.getEs('make',train_data)

array([7.52247339e-06, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.87608745e-02,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 7.36530302e-03, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00])

In [109]:
training.getLogEs('make',train_data)

C:\Shahar\BarIlan\NLP-courses\89680-NLP\assignment1\code\training.py:82: RuntimeWarning: divide by zero encountered in log


array([11.79761557,         inf,         inf,         inf,         inf,
               inf,         inf,         inf,         inf,         inf,
               inf,  3.97598172,         inf,         inf,         inf,
               inf,         inf,         inf,  4.91097509,         inf,
               inf,         inf,         inf,         inf,         inf,
               inf,         inf,         inf,         inf,         inf,
               inf,         inf,         inf,         inf,         inf,
               inf,         inf,         inf,         inf,         inf,
               inf,         inf,         inf,         inf,         inf])

In [103]:
len(train_data.word_counts['make'])

45

In [104]:
len(train_data.pos_counter)

45

In [195]:
a=[1,2,3]
a.reverse()
a


[3, 2, 1]

In [92]:
e=np.min(v,axis=0)
print(e.T)
print(np.tile(e,(5,1)))

[0.03069406 0.04529662 0.04385221]
[[0.03069406 0.04529662 0.04385221]
 [0.03069406 0.04529662 0.04385221]
 [0.03069406 0.04529662 0.04385221]
 [0.03069406 0.04529662 0.04385221]
 [0.03069406 0.04529662 0.04385221]]


### testing viterbi

In [284]:
import config
reload(config)
import training
reload(training)
import viterbi
reload(viterbi)
trigram_viterbi = viterbi.trigram_viterbi
another_viterbi = viterbi.another_viterbi

In [180]:
train_data_partial = training.read_input('..\\data\\ass1-tagger-train',['VBD','JJ','PRP$','VBZ'])

In [207]:
train_data = training.read_input('..\\data\\ass1-tagger-train')

In [219]:
training.getEs('electronics',train_data)

array([0.00011284, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.00056803, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        ])

In [181]:
train_data_partial.pos_items

OrderedDict([('*', 0), ('JJ', 1), ('VBD', 2), ('VBZ', 3), ('PRP$', 4)])

In [285]:
v, bp, y =another_viterbi(['Bell', 'makes','and','distributes','electronics'], train_data)
y

first_word_state_probabilities [       inf        inf 9.23115567        inf        inf        inf
        inf        inf        inf        inf        inf        inf
        inf        inf        inf        inf        inf        inf
        inf        inf        inf        inf        inf        inf
        inf        inf        inf        inf        inf        inf
        inf        inf        inf        inf        inf        inf
        inf        inf        inf        inf        inf        inf
        inf        inf        inf        inf]


[2, 14, 13, 14, 6]

In [280]:
v, bp, y = another_viterbi(['Chief', 'analyst','says','group','likely'], train_data)
y

first_word_state_probabilities [        inf         inf 10.32976796         inf         inf 14.29561545
         inf         inf         inf         inf         inf         inf
         inf         inf         inf         inf         inf         inf
         inf         inf         inf         inf         inf         inf
         inf         inf         inf         inf         inf         inf
         inf         inf         inf         inf         inf         inf
         inf         inf         inf         inf         inf         inf
         inf         inf         inf         inf]


[-1, -1, -1, 5, 0]

In [287]:
"(.{,2}\.)+"

'(.{,2}\\.)+'

In [273]:
y


[2, 0, 14, 25, 21]

In [263]:
train_data.pos_items

OrderedDict([('NN', 0),
             ('IN', 1),
             ('NNP', 2),
             ('DT', 3),
             ('*', 4),
             ('JJ', 5),
             ('NNS', 6),
             (',', 7),
             ('.', 8),
             ('CD', 9),
             ('RB', 10),
             ('VBD', 11),
             ('VB', 12),
             ('CC', 13),
             ('VBZ', 14),
             ('VBN', 15),
             ('PRP', 16),
             ('VBG', 17),
             ('TO', 18),
             ('VBP', 19),
             ('MD', 20),
             ('POS', 21),
             ('PRP$', 22),
             ('$', 23),
             ('``', 24),
             ("''", 25),
             (':', 26),
             ('WDT', 27),
             ('JJR', 28),
             ('NNPS', 29),
             ('RP', 30),
             ('WP', 31),
             ('WRB', 32),
             ('JJS', 33),
             ('RBR', 34),
             (')', 35),
             ('(', 36),
             ('EX', 37),
             ('RBS', 38),
             ('PDT', 39

In [259]:
bp

[array([[-1, -1, -1, ..., -1, -1, -1],
        [-1, -1, -1, ..., -1, -1, -1],
        [-1, -1, -1, ..., -1, -1, -1],
        ...,
        [-1, -1, -1, ..., -1, -1, -1],
        [-1, -1, -1, ..., -1, -1, -1],
        [-1, -1, -1, ..., -1, -1, -1]]), array([[-1, -1, -1, ..., -1, -1, -1],
        [-1, -1, -1, ..., -1, -1, -1],
        [-1, -1, -1, ..., -1, -1, -1],
        ...,
        [-1, -1, -1, ..., -1, -1, -1],
        [-1, -1, -1, ..., -1, -1, -1],
        [-1, -1, -1, ..., -1, -1, -1]]), array([[-1, -1, -1, ..., -1, -1, -1],
        [-1, -1, -1, ..., -1, -1, -1],
        [-1, -1, -1, ..., -1, -1, -1],
        ...,
        [-1, -1, -1, ..., -1, -1, -1],
        [-1, -1, -1, ..., -1, -1, -1],
        [-1, -1, -1, ..., -1, -1, -1]])]

In [203]:

# v, bp, y =another_viterbi(['proposed', 'limited','protected','experienced'], train_data_partial)
v, bp, y =another_viterbi(['last', 'new','chief','payable'], train_data_partial)


y: [0, 0]


In [242]:
v[1][2,14]

17.091471500836086

In [244]:
train_data.pos_items

OrderedDict([('NN', 0),
             ('IN', 1),
             ('NNP', 2),
             ('DT', 3),
             ('*', 4),
             ('JJ', 5),
             ('NNS', 6),
             (',', 7),
             ('.', 8),
             ('CD', 9),
             ('RB', 10),
             ('VBD', 11),
             ('VB', 12),
             ('CC', 13),
             ('VBZ', 14),
             ('VBN', 15),
             ('PRP', 16),
             ('VBG', 17),
             ('TO', 18),
             ('VBP', 19),
             ('MD', 20),
             ('POS', 21),
             ('PRP$', 22),
             ('$', 23),
             ('``', 24),
             ("''", 25),
             (':', 26),
             ('WDT', 27),
             ('JJR', 28),
             ('NNPS', 29),
             ('RP', 30),
             ('WP', 31),
             ('WRB', 32),
             ('JJS', 33),
             ('RBR', 34),
             (')', 35),
             ('(', 36),
             ('EX', 37),
             ('RBS', 38),
             ('PDT', 39

In [189]:
for w, v in train_data_partial.word_counts.items():
    if np.sum(v>0)>1:
        print(w, v)

increased [  0  17 128   0   0]
proposed [ 0 40 32  0  0]
disputed [0 2 4 0 0]
required [ 0 10 15  0  0]
added [  0   7 261   0   0]
limited [ 0 60  4  0  0]
announced [  0   4 153   0   0]
offered [ 0  4 69  0  0]
followed [ 0  1 40  0  0]
featured [0 1 4 0 0]
recorded [ 0  3 11  0  0]
liberated [0 1 1 0 0]
left [ 0  6 66  0  0]
converted [0 2 4 0 0]
continued [ 0 31 88  0  0]
cut [ 0  1 36  0  0]
attached [0 1 4 0 0]
supposed [0 1 2 0 0]
triggered [ 0  1 20  0  0]
injured [0 5 1 0 0]
protected [0 2 3 0 0]
allowed [ 0  1 26  0  0]
reported [  0   6 305   0   0]
resigned [ 0  1 74  0  0]
retired [ 0  8 10  0  0]
tried [ 0  1 41  0  0]
forced [ 0  5 19  0  0]
used [ 0  7 77  0  0]
worried [ 0 15  4  0  0]
received [  0   1 115   0   0]
troubled [ 0 38  2  0  0]
traded [ 0  4 31  0  0]
capped [ 0  3 14  0  0]
prepared [ 0 21  6  0  0]
closed [  0  29 286   0   0]
observed [ 0  2 10  0  0]
agreed [  0   1 211   0   0]
noted [  0   1 128   0   0]
suggested [ 0  1 31  0  0]
calculated [0 3 

In [206]:
for a in v:
    print(f'{a}\n')

[[       inf 5.39895641        inf        inf        inf]
 [       inf 5.39895641        inf        inf        inf]
 [       inf 5.39895641        inf        inf        inf]
 [       inf 5.39895641        inf        inf        inf]
 [       inf 5.39895641        inf        inf        inf]]

[[        inf         inf         inf         inf         inf]
 [        inf 10.19460437         inf         inf         inf]
 [        inf         inf         inf         inf         inf]
 [        inf         inf         inf         inf         inf]
 [        inf         inf         inf         inf         inf]]

[[       inf        inf        inf        inf        inf]
 [       inf 16.5211737        inf        inf        inf]
 [       inf        inf        inf        inf        inf]
 [       inf        inf        inf        inf        inf]
 [       inf        inf        inf        inf        inf]]

[[        inf         inf         inf         inf         inf]
 [        inf 25.08028427         in

In [192]:
for a in v:
    print(f'{a}\n')

[[       inf 8.62480785 8.2721253         inf        inf]
 [       inf 8.62480785 8.2721253         inf        inf]
 [       inf 8.62480785 8.2721253         inf        inf]
 [       inf 8.62480785 8.2721253         inf        inf]
 [       inf 8.62480785 8.2721253         inf        inf]]

[[        inf         inf         inf         inf         inf]
 [        inf 16.57247933 19.11194738         inf         inf]
 [        inf 16.149827   18.864671           inf         inf]
 [        inf         inf         inf         inf         inf]
 [        inf         inf         inf         inf         inf]]

[[        inf         inf         inf         inf         inf]
 [        inf 24.54261576 24.78613899         inf         inf]
 [        inf 27.1923619  27.50676067         inf         inf]
 [        inf         inf         inf         inf         inf]
 [        inf         inf         inf         inf         inf]]

[[        inf         inf         inf         inf         inf]
 [        i

In [150]:
for x in np.array([1,2,3]):
    print(x)

1
2
3


In [131]:
train_data_partial.pos_items

OrderedDict([('NN', 0),
             ('JJ', 1),
             ('*', 2),
             ('**', 3),
             ('VBZ', 4),
             ('PRP$', 5)])

In [132]:
t =[['a','b','c'],['d','e','f']]
x = [f for f in t]
print(x)

[['a', 'b', 'c'], ['d', 'e', 'f']]


In [134]:
a = Counter()
a.update(['a','b','c'])
a.update('b')
a.update('a')
print(a)

Counter({'a': 2, 'b': 2, 'c': 1})


In [137]:
for t in a.most_common():
    print(t)

('a', 2)
('b', 2)
('c', 1)


In [14]:
import test
reload(test)
food_train_data = test.food_train_data

#### test using food train data

In [15]:
food_train_data

training_data(pos_items=OrderedDict([('start', 0), ('oeuvre', 1), ('main', 2), ('side', 3), ('drink', 4), ('dessert', 5)]), pos_counter=array([30, 15, 43, 30, 31, 22]), pos_counter1=array([[ 0, 10, 10,  4,  4,  2],
       [ 0,  1,  8,  2,  4,  0],
       [ 0,  1,  9, 10,  8, 12],
       [ 0,  0,  2, 10,  5,  5],
       [ 0,  3, 11,  4,  4,  1],
       [ 0,  0,  3,  0,  6,  2]]), pos_counter2=Counter({('oeuvre', 'oeuvre', 'oeuvre'): 16, ('oeuvre', 'oeuvre', 'side'): 7, ('oeuvre', 'side', 'main'): 6, ('start', 'oeuvre', 'side'): 5, ('start', 'drink', 'oeuvre'): 5, ('start', 'oeuvre', 'oeuvre'): 4, ('start', 'side', 'main'): 4, ('side', 'main', 'drink'): 4, ('drink', 'oeuvre', 'oeuvre'): 4, ('start', 'start', 'oeuvre'): 3, ('start', 'oeuvre', 'main'): 3, ('start', 'side', 'drink'): 3, ('oeuvre', 'oeuvre', 'dessert'): 3, ('oeuvre', 'main', 'oeuvre'): 3, ('side', 'main', 'oeuvre'): 3, ('dessert', 'oeuvre', 'oeuvre'): 3, ('start', 'start', 'start'): 2, ('start', 'start', 'side'): 2, ('start'

In [146]:
import training
reload(training)

import viterbi
reload(viterbi)
trigram_viterbi = viterbi.trigram_viterbi


import config
reload(config)
config.period='start'

In [21]:
trigram_viterbi(['soup','egg','ham'],food_train_data)

C:\Shahar\BarIlan\NLP-courses\89680-NLP\assignment1\code\training.py:94: RuntimeWarning: divide by zero encountered in log
  return -np.log(train_data.word_counts[word]) + np.log(train_data.pos_counter)
C:\Shahar\BarIlan\NLP-courses\89680-NLP\assignment1\code\training.py:82: RuntimeWarning: divide by zero encountered in long_scalars
  components = np.array([count_abc/count_ab, count_bc/count_b, count_c/numwords])
C:\Shahar\BarIlan\NLP-courses\89680-NLP\assignment1\code\training.py:82: RuntimeWarning: invalid value encountered in long_scalars
  components = np.array([count_abc/count_ab, count_bc/count_b, count_c/numwords])
C:\Shahar\BarIlan\NLP-courses\89680-NLP\assignment1\code\viterbi.py:64: RuntimeWarning: invalid value encountered in add
  V_r_tp = q_r_tp + np.tile(e_w_r,(T,1))
C:\ProgramData\Anaconda3\envs\bari_env\lib\site-packages\numpy\core\fromnumeric.py:83: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)


[0, 0, 0, 0, 0]

In [86]:
train_data = food_train_data
sentence = ['soup','egg','ham']

period = config.period
pos_items = train_data.pos_items
T = len(train_data.pos_items)
V = np.zeros((T,T),np.double)
V[pos_items[period],pos_items[period]] = 1
bp = []


In [64]:
siter = iter(sentence)


In [65]:
#for word in sentence:
word = next(siter)
piiter = iter(enumerate(pos_items))

In [66]:
citer = iter(enumerate(pos_items))
bp_n = -np.ones((T,T),np.int)
e_w_r = training.getLogEs(word,train_data) # return a vector with entry per POS

In [67]:





# for t,b in enumerate(pos_items):
t, b = next(piiter)
q_r_tp = np.zeros((T,T),np.double)
#for r,c in enumerate(pos_items):




In [75]:
r,c = next(citer)
search_triplets = [(tp,b,c) for tp in pos_items]
q_r_tp[r,:] = np.array([training.getLogQ(triplet,train_data) for triplet in search_triplets])
    
print(r,c)

StopIteration: 

In [87]:
V_r_tp = q_r_tp + np.tile(e_w_r,(T,1))
V_r_tp

array([[       inf, 2.65675691, 2.50593402, 3.06222201, 3.09501184,
               inf],
       [       inf, 2.53159376, 2.38077087, 2.93705887, 2.96984869,
               inf],
       [       inf, 1.9308199 , 1.77999701, 2.33628501, 2.36907483,
               inf],
       [       inf, 2.43095024, 2.28012735, 2.83641535, 2.86920517,
               inf],
       [       inf, 2.40470201, 2.25387912, 2.81016712, 2.84295694,
               inf],
       [       inf, 2.8075798 , 2.65675691, 3.2130449 , 3.24583473,
               inf]])

In [88]:
V

array([[1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [90]:
t

0

In [89]:
V_r_tp += np.tile(V[t,:],(T,1)).T
V_r_tp

array([[       inf, 3.65675691, 3.50593402, 4.06222201, 4.09501184,
               inf],
       [       inf, 2.53159376, 2.38077087, 2.93705887, 2.96984869,
               inf],
       [       inf, 1.9308199 , 1.77999701, 2.33628501, 2.36907483,
               inf],
       [       inf, 2.43095024, 2.28012735, 2.83641535, 2.86920517,
               inf],
       [       inf, 2.40470201, 2.25387912, 2.81016712, 2.84295694,
               inf],
       [       inf, 2.8075798 , 2.65675691, 3.2130449 , 3.24583473,
               inf]])

In [91]:

V_r = np.min(V_r_tp, axis=0)
V[t,:] = V_r
bp_n[t,:]=np.argmin(V_r_tp,axis=0)

bp.append(bp_n)

In [92]:
V_r

array([       inf, 1.9308199 , 1.77999701, 2.33628501, 2.36907483,
              inf])

In [93]:
V

array([[       inf, 1.9308199 , 1.77999701, 2.33628501, 2.36907483,
               inf],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ]])

In [94]:
np.argmin(V_r_tp,axis=0)

array([0, 2, 2, 2, 2, 0], dtype=int64)

In [82]:
e_w_r

array([       inf, 1.60943791, 1.45861502, 2.01490302, 2.04769284,
              inf])

In [59]:
e_w_r = training.getLogEs('soup',train_data)
print(e_w_r)

[       inf 1.60943791 1.45861502 2.01490302 2.04769284        inf]


In [60]:
t,b

(0, 'start')

In [61]:
r,c

(0, 'start')

In [78]:
search_triplets

[('start', 'start', 'dessert'),
 ('oeuvre', 'start', 'dessert'),
 ('main', 'start', 'dessert'),
 ('side', 'start', 'dessert'),
 ('drink', 'start', 'dessert'),
 ('dessert', 'start', 'dessert')]

In [76]:
q_r_tp

array([[1.04731899, 1.04731899, 1.04731899, 1.04731899, 1.04731899,
        1.04731899],
       [0.92215585, 0.92215585, 0.92215585, 0.92215585, 0.92215585,
        0.92215585],
       [0.32138199, 0.32138199, 0.32138199, 0.32138199, 0.32138199,
        0.32138199],
       [0.82151233, 0.82151233, 0.82151233, 0.82151233, 0.82151233,
        0.82151233],
       [0.7952641 , 0.7952641 , 0.7952641 , 0.7952641 , 0.7952641 ,
        0.7952641 ],
       [1.19814188, 1.19814188, 1.19814188, 1.19814188, 1.19814188,
        1.19814188]])

In [33]:
search_triplets

[('start', 'start', 'dessert'),
 ('oeuvre', 'start', 'dessert'),
 ('main', 'start', 'dessert'),
 ('side', 'start', 'dessert'),
 ('drink', 'start', 'dessert'),
 ('dessert', 'start', 'dessert')]

In [54]:
[ training.getQ(t,food_train_data) for t in search_triplets]

[0.3508771929824561,
 0.3508771929824561,
 0.3508771929824561,
 0.3508771929824561,
 0.3508771929824561,
 0.3508771929824561]

In [98]:
bp

[array([[ 0,  2,  2,  2,  2,  0],
        [-1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1]])]

In [144]:
a=np.ones((5,5))
print(a[:,3].T)
print(np.tile(a[:,3],(1,2)))

[1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
y_n = [np.argmin(V), np.argmin(V)]
for bp_i in bp[2::-1]:
    y_n = [bp_i[y_n[0],y_n[1]]] + y_n