In [3]:
import numpy as np
from itertools import chain

In [1]:
tagsdict = {'CC': 'Coordinating conjunction',
'CD': 'Cardinal number',
'DT': 'Determiner',
'EX': 'Existential there',
'FW': 'Foreign word',
'IN': 'Preposition or subordinating conjunction',
'JJ': 'Adjective',
'JJR': 'Adjective, comparative',
'JJS': 'Adjective, superlative',
'LS': 'List item marker',
'MD': 'Modal',
'NN': 'Noun, singular or mass',
'NNS': 'Noun, plural',
'NNP': 'Proper noun, singular',
'NNPS': 'Proper noun, plural',
'PDT': 'Predeterminer',
'POS': 'Possessive ending',
'PRP': 'Personal pronoun',
'PRP$': 'Possessive pronoun',
'RB': 'Adverb',
'RBR': 'Adverb, comparative',
'RBS': 'Adverb, superlative',
'RP': 'Particle',
'SYM': 'Symbol',
'TO': 'to',
'UH': 'Interjection',
'VB': 'Verb, base form',
'VBD': 'Verb, past tense',
'VBG': 'Verb, gerund or present participle',
'VBN': 'Verb, past participle',
'VBP': 'Verb, non-3rd person singular present',
'VBZ': 'Verb, 3rd person singular present',
'WDT': 'Wh-determiner',
'WP': 'Wh-pronoun',
'WP$': 'Possessive wh-pronoun',
'WRB': 'Wh-adverb'}

In [5]:
sample = 'holly/nnp came/vbd from/in miami/nnp ,/, Fla./nnp ,/, '+\
'hitch-hiked/vbd her/prp way/nn across/in the/dt usa/nnp'

In [6]:
import string
analyzed_sample = [(a,str.upper(b)) for a, b in [w.split('/') for w in sample.split(' ')]]
print(analyzed_sample)

[('holly', 'NNP'), ('came', 'VBD'), ('from', 'IN'), ('miami', 'NNP'), (',', ','), ('Fla.', 'NNP'), (',', ','), ('hitch-hiked', 'VBD'), ('her', 'PRP'), ('way', 'NN'), ('across', 'IN'), ('the', 'DT'), ('usa', 'NNP')]


In [7]:
for word, pos in analyzed_sample:
    print('{}: {} ({})'.format(word, pos, tagsdict[pos] if pos in tagsdict else '?'))

holly: NNP (Proper noun, singular)
came: VBD (Verb, past tense)
from: IN (Preposition or subordinating conjunction)
miami: NNP (Proper noun, singular)
,: , (?)
Fla.: NNP (Proper noun, singular)
,: , (?)
hitch-hiked: VBD (Verb, past tense)
her: PRP (Personal pronoun)
way: NN (Noun, singular or mass)
across: IN (Preposition or subordinating conjunction)
the: DT (Determiner)
usa: NNP (Proper noun, singular)


In [5]:
layer_nodes = [
['seattle','newport','sf','usc'],
['boise','salt lake','las vegas','tucson'],
['Casper','denver','albequerque','el paso'],
['pierre','lincoln','amarillo','san antonio'],
['minneapolis','kansas city','ft. smith','houston'],
['chicago','st louis','nashville','new orleans'],
['pittsburg','roanoke','charlotte','tallahassee'],
['mit','washingto','wilmington','daytona beach']]

In [6]:
# the "states"
S = list(chain(*layer_nodes))
print(S)

['seattle', 'newport', 'sf', 'usc', 'boise', 'salt lake', 'las vegas', 'tucson', 'Casper', 'denver', 'albequerque', 'el paso', 'pierre', 'lincoln', 'amarillo', 'san antonio', 'minneapolis', 'kansas city', 'ft. smith', 'houston', 'chicago', 'st louis', 'nashville', 'new orleans', 'pittsburg', 'roanoke', 'charlotte', 'tallahassee', 'mit', 'washingto', 'wilmington', 'daytona beach']


In [10]:
layer_distance =[ 
    np.array([
    [494,0,0,0],
    [561,0,0,0],
    [648,748,630,0],
    [0,0,275,528]
    ]),np.array([
[669,0,0,0],
[402,493,609,0],
[0,0,576,724],
[0,0,452,320],
    ]),np.array([
        [347,635,705,0],
[526,667,424,0],
[0,0,288,714],
[0,0,421,555],
    ]),np.array([
        [478,598,0,0],
[438,207,567,0],
[0,613,539,614],
[0,0,635,199],
    ]),np.array([
        [465,593,0,0],
[527,256,618,0],
[0,545,501,601],
[0,0,635,352],
    ]),np.array([
        [532,717,0,0],
[659,689,0,0],
[0,435,434,495],
[0,0,725,388],
    ]),np.array([
[680,259,0,0],
[0,233,306,0],
[0,397,206,480],
[0,0,496,316]
    ])
]
for m in layer_distance:
    m[m==0]= 10000
print(layer_distance)

[array([[  494, 10000, 10000, 10000],
       [  561, 10000, 10000, 10000],
       [  648,   748,   630, 10000],
       [10000, 10000,   275,   528]]), array([[  669, 10000, 10000, 10000],
       [  402,   493,   609, 10000],
       [10000, 10000,   576,   724],
       [10000, 10000,   452,   320]]), array([[  347,   635,   705, 10000],
       [  526,   667,   424, 10000],
       [10000, 10000,   288,   714],
       [10000, 10000,   421,   555]]), array([[  478,   598, 10000, 10000],
       [  438,   207,   567, 10000],
       [10000,   613,   539,   614],
       [10000, 10000,   635,   199]]), array([[  465,   593, 10000, 10000],
       [  527,   256,   618, 10000],
       [10000,   545,   501,   601],
       [10000, 10000,   635,   352]]), array([[  532,   717, 10000, 10000],
       [  659,   689, 10000, 10000],
       [10000,   435,   434,   495],
       [10000, 10000,   725,   388]]), array([[  680,   259, 10000, 10000],
       [10000,   233,   306, 10000],
       [10000,   397,   2

In [12]:
# now create one big state matrix
def create_big_state_matrix(layer_distance):
    ls = 4
    layers = 8
    cities_west_start_index=0
    cities_east_start_index=ls
    res = np.zeros((ls*layers, ls*layers), np.int)
    for arr in layer_distance:
        res[cities_west_start_index: (cities_west_start_index+ls),
           cities_east_start_index: (cities_east_start_index+ls)] = arr
        cities_west_start_index += ls
        cities_east_start_index += ls

    # print(res)
    return res

In [34]:
res[-8:,-8:]

array([[    0,     0,     0,     0,   680,   259, 10000, 10000],
       [    0,     0,     0,     0, 10000,   233,   306, 10000],
       [    0,     0,     0,     0, 10000,   397,   206,   480],
       [    0,     0,     0,     0, 10000, 10000,   496,   316],
       [    0,     0,     0,     0,     0,     0,     0,     0],
       [    0,     0,     0,     0,     0,     0,     0,     0],
       [    0,     0,     0,     0,     0,     0,     0,     0],
       [    0,     0,     0,     0,     0,     0,     0,     0]])

In [1]:
#import sys
#sys.path.append("C:\\Shahar\\BarIlan\\NLP-courses\\89680-NLP\\assignment1\\code")

In [2]:
from viterbi import viterbi

In [14]:
ls = 4
layers = 8
res = create_big_state_matrix(layer_distance)
res[res==0]=10000
res = np.concatenate([np.zeros((ls*layers,1)), res],axis=1)
res[ls:,0]=10000
res = np.concatenate([10000*np.ones((1,ls*layers+1)), res])


In [17]:
viterbi(7,res,1,len(S)+1)

J: 1
V=
[[ 1.e+00  1.e+04 -1.e+03 -1.e+03 -1.e+03 -1.e+03 -1.e+03]
 [ 1.e+00  1.e+04 -1.e+03 -1.e+03 -1.e+03 -1.e+03 -1.e+03]
 [ 1.e+00  1.e+04 -1.e+03 -1.e+03 -1.e+03 -1.e+03 -1.e+03]
 [ 1.e+00  1.e+04 -1.e+03 -1.e+03 -1.e+03 -1.e+03 -1.e+03]
 [ 1.e+00  1.e+04 -1.e+03 -1.e+03 -1.e+03 -1.e+03 -1.e+03]
 [ 1.e+00  1.e+04 -1.e+03 -1.e+03 -1.e+03 -1.e+03 -1.e+03]
 [ 1.e+00  1.e+04 -1.e+03 -1.e+03 -1.e+03 -1.e+03 -1.e+03]
 [ 1.e+00  1.e+04 -1.e+03 -1.e+03 -1.e+03 -1.e+03 -1.e+03]
 [ 1.e+00  1.e+04 -1.e+03 -1.e+03 -1.e+03 -1.e+03 -1.e+03]
 [ 1.e+00  1.e+04 -1.e+03 -1.e+03 -1.e+03 -1.e+03 -1.e+03]
 [ 1.e+00  1.e+04 -1.e+03 -1.e+03 -1.e+03 -1.e+03 -1.e+03]
 [ 1.e+00  1.e+04 -1.e+03 -1.e+03 -1.e+03 -1.e+03 -1.e+03]
 [ 1.e+00  1.e+04 -1.e+03 -1.e+03 -1.e+03 -1.e+03 -1.e+03]
 [ 1.e+00  1.e+04 -1.e+03 -1.e+03 -1.e+03 -1.e+03 -1.e+03]
 [ 1.e+00  1.e+04 -1.e+03 -1.e+03 -1.e+03 -1.e+03 -1.e+03]
 [ 1.e+00  1.e+04 -1.e+03 -1.e+03 -1.e+03 -1.e+03 -1.e+03]
 [ 1.e+00  1.e+04 -1.e+03 -1.e+03 -1.e+03 -1.e+0

In [16]:
len(S)

32

In [34]:
a = np.concatenate([np.inf*np.ones((3,3)), np.array([[1,2,3]])])
print(a)
print(np.min(a,axis=1))

[[inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [ 1.  2.  3.]]
[inf inf inf  1.]


In [72]:
from importlib import reload
import viterbi
reload(viterbi)
from viterbi import viterbi_sparse

see http://www.cim.mcgill.ca/~latorres/Viterbi/va_alg.htm


In [73]:
eg=[[(0,0,1),(0,2,1)],
[(0,0,1),(0,2,1),(2,1,2),(2,3,0)],
[(0,0,0),(0,2,2),(1,0,2),(1,2,0),(2,1,1),(2,3,1),(3,1,1),(3,3,1)],
[(0,0,2),(1,0,0),(2,1,1),(3,1,1)],
[(0,0,1),(1,0,1)]]
print(eg)

[[(0, 0, 1), (0, 2, 1)], [(0, 0, 1), (0, 2, 1), (2, 1, 2), (2, 3, 0)], [(0, 0, 0), (0, 2, 2), (1, 0, 2), (1, 2, 0), (2, 1, 1), (2, 3, 1), (3, 1, 1), (3, 3, 1)], [(0, 0, 2), (1, 0, 0), (2, 1, 1), (3, 1, 1)], [(0, 0, 1), (1, 0, 1)]]


In [75]:
S, l_total,path = viterbi_sparse(eg,4)

layer 0:v
 [[ 1. inf  1. inf]
 [inf inf inf inf]
 [inf inf inf inf]
 [inf inf inf inf]]
next_L
[ 1. inf  1. inf]
layer 1:v
 [[ 2. inf  2. inf]
 [inf inf inf inf]
 [inf  3. inf  1.]
 [inf inf inf inf]]
next_L
[2. 3. 2. 1.]
layer 2:v
 [[ 2. inf  4. inf]
 [ 5. inf  3. inf]
 [inf  3. inf  3.]
 [inf  2. inf  2.]]
next_L
[2. 2. 3. 2.]
layer 3:v
 [[ 4. inf inf inf]
 [ 2. inf inf inf]
 [inf  4. inf inf]
 [inf  3. inf inf]]
next_L
[ 2.  3. inf inf]
layer 4:v
 [[ 3. inf inf inf]
 [ 4. inf inf inf]
 [inf inf inf inf]
 [inf inf inf inf]]
next_L
[ 3. inf inf inf]


In [70]:
S

[array([0, 0, 0, 0], dtype=int64),
 array([0, 2, 0, 2], dtype=int64),
 array([0, 3, 1, 3], dtype=int64),
 array([1, 3, 0, 0], dtype=int64),
 array([0, 0, 0, 0], dtype=int64)]

In [76]:
path

[0, 2, 3, 1, 0, 0]

In [47]:
l_total

1.0