In [2]:
from scipy.special import softmax
import numpy as np

In [3]:
x = np.arange(2,5,0.5)
x

array([2. , 2.5, 3. , 3.5, 4. , 4.5])

In [5]:
y = softmax(x)
y

array([0.0339902 , 0.05604037, 0.09239495, 0.15233352, 0.25115552,
       0.41408544])

In [10]:
y_hat = 1
loss = lambda x: np.log(softmax(x)[y_hat])
loss(x)

-2.881682948624487

In [7]:
x1 = x.copy()
dx = y.copy()
dx[y_hat] -=1
dx

array([ 0.0339902 , -0.94395963,  0.09239495,  0.15233352,  0.25115552,
        0.41408544])

In [15]:
x1 = x.copy()
x1[1] += 1e-4 * dx[1]
loss(x1) - loss(x)

-8.910621391589046e-05

In [34]:
for i in range(4):
    x1 = x.copy()
    x1[i] += 1e-3 
    print(loss(x1) - loss(x)+ dx[i] * 1e-3)


-1.64225362266914e-08
-2.6457753851726398e-08
-4.1940457529962344e-08
-6.457897544688172e-08


In [24]:



def cross_entropy(X,y):
    """
    X is the output from fully connected layer (num_examples x num_classes)
    y is labels (num_examples x 1)
    	Note that y is not one-hot encoded vector. 
    	It can be computed as y.argmax(axis=1) from one-hot encoded vectors of labels if required.
    """
    m = y.shape[0]
    p = softmax(X)
    # We use multidimensional array indexing to extract 
    # softmax probability of the correct label for each sample.
    # Refer to https://docs.scipy.org/doc/numpy/user/basics.indexing.html#indexing-multi-dimensional-arrays for understanding multidimensional array indexing.
    log_likelihood = -np.log(p[range(m),y])
    loss = np.sum(log_likelihood) / m
    return loss



def delta_cross_entropy(X,y):
    """
    X is the output from fully connected layer (num_examples x num_classes)
    y is labels (num_examples x 1)
    	Note that y is not one-hot encoded vector. 
    	It can be computed as y.argmax(axis=1) from one-hot encoded vectors of labels if required.
    """
    m = y.shape[0]
    grad = softmax(X)
    grad[range(m),y] -= 1
    grad = grad/m
    return grad

In [28]:
cross_entropy(x[np.newaxis,:],np.array([y_hat]))

2.881682948624487

In [29]:
delta_cross_entropy(x[np.newaxis,:],np.array([y_hat]))

array([[ 0.0339902 , -0.94395963,  0.09239495,  0.15233352,  0.25115552,
         0.41408544]])

In [ ]:
xx = x[np.newaxis,:]
dxx = delta_cross_entropy(x[np.newaxis,:],np.array([y_hat]))
xx[0] = xx[0] + 1e-4
